/* tether M2: C host — Lua 5.4.6 embedded, raw-mode terminal, tether API */
#define _XOPEN_SOURCE 500
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <sys/select.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h> /* WEXITSTATUS in l_exec */
#include <dirent.h>
#include <fcntl.h>
#include <termios.h>
#include <sys/ioctl.h>
#include <limits.h>
#include <strings.h>
#include <poll.h>
#include <time.h>
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#include <curl/curl.h>

/* Vendor'd krep engine (grep backend). Its header also defines file-scope
   skip lists that only krep.c itself consumes; silence the unused-variable
   warnings those would otherwise raise here under -Werror. */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-const-variable"
#include "krep.h"
#pragma GCC diagnostic pop

/* embedded Lua sources (generated by tools/embed.lua) */
#include "embed.c"

static struct termios orig_termios;
static int termios_active = 0;

/* --- Ctrl+C while a turn blocks -------------------------------------------
   Raw mode clears ISIG, so an in-terminal Ctrl+C arrives as byte 0x03 rather
   than SIGINT, and the UI reads input only between turns — exactly when no turn
   is running. While a turn blocks (tether.sleep, an in-flight HTTP transfer)
   the host therefore watches stdin itself: 0x03 raises `g_interrupt`, and every
   other byte is queued so read_char still delivers it. That way a Ctrl+C can
   stop the turn it was meant for, without losing a keystroke. */
#define PENDING_CAP 256
static unsigned char g_pending[PENDING_CAP];
static size_t g_pending_len = 0; /* bytes queued */
static size_t g_pending_pos = 0; /* bytes handed back */
static int g_interrupt = 0;
static int g_stdin_eof = 0; /* stop watching once input is exhausted */

/* Take one queued byte, if any. */
static int pending_take(unsigned char *out)
{
    if (g_pending_pos >= g_pending_len) {
        g_pending_len = g_pending_pos = 0;
        return 0;
    }
    *out = g_pending[g_pending_pos++];
    return 1;
}

/* Non-blocking: queue every available byte, remember a Ctrl+C. Returns non-zero
   when an interrupt is pending. Never blocks and never delays a caller. */
static int poll_interrupt(void)
{
    if (g_stdin_eof) return g_interrupt;
    for (;;) {
        struct pollfd pfd;
        pfd.fd = STDIN_FILENO;
        pfd.events = POLLIN;
        pfd.revents = 0;
        int rc = poll(&pfd, 1, 0);
        if (rc <= 0) break;
        unsigned char buf[64];
        ssize_t n = read(STDIN_FILENO, buf, sizeof buf);
        if (n <= 0) {
            if (n == 0) g_stdin_eof = 1; /* pipes: nothing more will arrive */
            else if (errno != EINTR && errno != EAGAIN) g_stdin_eof = 1;
            break;
        }
        for (ssize_t i = 0; i < n; i++) {
            if (buf[i] == 3) {
                g_interrupt = 1;
            } else if (g_pending_len - g_pending_pos < PENDING_CAP) {
                g_pending[g_pending_len++] = buf[i];
            }
        }
    }
    return g_interrupt;
}

/* libcurl progress callback: abort an in-flight transfer as soon as Ctrl+C
   arrives, so a stalled stream cannot hold the turn. */
static int http_xferinfo(void *clientp, curl_off_t dltotal, curl_off_t dlnow,
                         curl_off_t ultotal, curl_off_t ulnow)
{
    (void)clientp; (void)dltotal; (void)dlnow; (void)ultotal; (void)ulnow;
    return poll_interrupt() ? 1 : 0;
}

static void restore_termios(void)
{
    if (termios_active) {
        tcsetattr(STDIN_FILENO, TCSANOW, &orig_termios);
        printf("\x1b[?25h\n");
        fflush(stdout);
        termios_active = 0;
    }
}

static volatile sig_atomic_t g_resize_requested = 0;

/* SIGTERM/SIGINT: restore the terminal (a no-op when raw mode was never
   enabled) and exit cleanly. Raw mode disables ISIG, so an in-terminal
   Ctrl+C arrives as byte 0x03 and only an external signal lands here. */
static void on_exit_signal(int sig)
{
    (void)sig;
    restore_termios();
    _exit(0);
}

static void on_sigwinch(int sig)
{
    (void)sig;
    g_resize_requested = 1;
}

static void setup_signal_handlers(void)
{
    struct sigaction sa_term, sa_winch;
    sa_term.sa_handler = on_exit_signal;
    sigemptyset(&sa_term.sa_mask);
    sa_term.sa_flags = 0;
    sigaction(SIGTERM, &sa_term, NULL);
    sigaction(SIGINT, &sa_term, NULL);
    sa_winch.sa_handler = on_sigwinch;
    sigemptyset(&sa_winch.sa_mask);
    sa_winch.sa_flags = SA_RESTART;
    sigaction(SIGWINCH, &sa_winch, NULL);
}

static int init_termios(void)
{
    struct termios raw;
    if (tcgetattr(STDIN_FILENO, &orig_termios) == -1)
        return -1;
    raw = orig_termios;
    raw.c_iflag &= ~(BRKINT | ICRNL | INPCK | ISTRIP | IXON);
    /* OPOST kept enabled: \n -> \r\n translation for proper line rendering */
    raw.c_cflag |= CS8;
    raw.c_lflag &= ~(ECHO | ICANON | ISIG | IEXTEN);
    raw.c_cc[VMIN] = 1;
    raw.c_cc[VTIME] = 0;
    if (tcsetattr(STDIN_FILENO, TCSANOW, &raw) == -1)
        return -1;
    termios_active = 1;
    return 0;
}

/* --- tether.* API exposed to Lua --- */

static int l_read_char(lua_State *L)
{
    /* bytes the watch picked up during a blocked turn come first */
    unsigned char queued;
    if (pending_take(&queued)) {
        lua_pushinteger(L, queued);
        return 1;
    }
    char c;
    ssize_t n = read(STDIN_FILENO, &c, 1);
    if (n != 1)
        lua_pushnil(L);
    else
        lua_pushinteger(L, (unsigned char)c);
    return 1;
}

static int l_read_char_nb(lua_State *L)
{
    unsigned char queued;
    if (pending_take(&queued)) {
        lua_pushinteger(L, queued);
        return 1;
    }
    fd_set fds;
    struct timeval tv;
    FD_ZERO(&fds);
    FD_SET(STDIN_FILENO, &fds);
    tv.tv_sec = 0;
    tv.tv_usec = 50000;
    int ready = select(STDIN_FILENO + 1, &fds, NULL, NULL, &tv);
    if (ready <= 0) { lua_pushnil(L); return 1; }
    char c;
    ssize_t n = read(STDIN_FILENO, &c, 1);
    if (n != 1)
        lua_pushnil(L);
    else
        lua_pushinteger(L, (unsigned char)c);
    return 1;
}

static int l_write(lua_State *L)
{
    size_t len;
    const char *s = luaL_checklstring(L, 1, &len);
    ssize_t w = write(STDOUT_FILENO, s, len);
    if (w == -1)
        luaL_error(L, "write: %s", strerror(errno));
    if (w != (ssize_t)len) {
        /* partial write: retry remaining bytes */
        const char *ptr = s + w;
        size_t remaining = len - w;
        while (remaining > 0) {
            w = write(STDOUT_FILENO, ptr, remaining);
            if (w == -1) break;
            ptr += w;
            remaining -= w;
        }
    }
    fflush(stdout);
    return 0;
}

static int l_exec(lua_State *L)
{
    const char *cmd = luaL_checkstring(L, 1);
    /* system() already runs via sh -c, so pass cmd directly */
    int code = system(cmd);
    int exit_code = WEXITSTATUS(code);
    lua_pushboolean(L, exit_code == 0);
    lua_pushinteger(L, exit_code);
    return 2;
}

static int l_realpath(lua_State *L)
{
    const char *path = luaL_checkstring(L, 1);
    char resolved[PATH_MAX];
    char *rp = realpath(path, resolved);
    if (rp == NULL) {
        lua_pushboolean(L, 0);
        return 1;
    }
    lua_pushstring(L, rp);
    return 1;
}

static int l_getcwd(lua_State *L)
{
    char buf[4096];
    if (getcwd(buf, sizeof(buf)) == NULL)
        luaL_error(L, "getcwd: %s", strerror(errno));
    lua_pushstring(L, buf);
    return 1;
}

static int l_get_terminal_size(lua_State *L)
{
    struct winsize ws;
    if (ioctl(STDIN_FILENO, TIOCGWINSZ, &ws) == 0) {
        lua_newtable(L);
        lua_pushinteger(L, ws.ws_col);
        lua_setfield(L, -2, "width");
        lua_pushinteger(L, ws.ws_row);
        lua_setfield(L, -2, "height");
    } else {
        lua_pushnil(L);
    }
    return 1;
}

static int l_tty(lua_State *L)
{
    lua_pushboolean(L, isatty(STDIN_FILENO) == 1);
    return 1;
}

/* --- fs API (mkdirp/fchmod/readdir/stat) --- */

/* qsort comparator for the directory-entry names collected by l_readdir */
static int fs_name_cmp(const void *a, const void *b)
{
    return strcmp(*(const char *const *)a, *(const char *const *)b);
}

/* tether.mkdirp(path) -> true | nil, err  (recursive; EEXIST ignored) */
static int l_mkdirp(lua_State *L)
{
    const char *path = luaL_checkstring(L, 1);
    size_t len = strlen(path);
    if (len == 0) {
        lua_pushnil(L);
        lua_pushstring(L, "empty path");
        return 2;
    }
    char *buf = malloc(len + 1);
    if (buf == NULL)
        return luaL_error(L, "mkdirp: out of memory");
    memcpy(buf, path, len + 1);

    /* create every prefix at each '/'; mkdir(2) reports EEXIST for the
       parts that already exist, which is the normal case when called twice */
    for (size_t i = 1; i <= len; i++) {
        if (buf[i] != '/' && buf[i] != '\0') continue;
        char saved = buf[i];
        buf[i] = '\0';
        int rc = mkdir(buf, 0777);
        int e = errno;
        buf[i] = saved;
        if (rc != 0 && e != EEXIST) {
            free(buf);
            lua_pushnil(L);
            lua_pushstring(L, strerror(e));
            return 2;
        }
    }

    /* the final component must resolve to a directory, not a file */
    struct stat st;
    if (stat(buf, &st) != 0 || !S_ISDIR(st.st_mode)) {
        int e = errno;
        free(buf);
        lua_pushnil(L);
        lua_pushstring(L, e != 0 ? strerror(e) : "not a directory");
        return 2;
    }
    free(buf);
    lua_pushboolean(L, 1);
    return 1;
}

/* tether.fchmod(path, mode) -> true | nil, err */
static int l_fchmod(lua_State *L)
{
    const char *path = luaL_checkstring(L, 1);
    int mode = (int)luaL_checkinteger(L, 2);
    int fd = open(path, O_WRONLY);
    if (fd < 0) {
        lua_pushnil(L);
        lua_pushstring(L, strerror(errno));
        return 2;
    }
    int rc = fchmod(fd, (mode_t)mode);
    int e = errno;
    close(fd);
    if (rc != 0) {
        lua_pushnil(L);
        lua_pushstring(L, strerror(e));
        return 2;
    }
    lua_pushboolean(L, 1);
    return 1;
}

/* tether.readdir(path) -> { names sorted, no . / .. } | nil, err */
static int l_readdir(lua_State *L)
{
    const char *path = luaL_checkstring(L, 1);
    DIR *dir = opendir(path);
    if (dir == NULL) {
        lua_pushnil(L);
        lua_pushstring(L, strerror(errno));
        return 2;
    }
    size_t cap = 32, len = 0;
    char **names = malloc(cap * sizeof(*names));
    if (names == NULL) {
        closedir(dir);
        return luaL_error(L, "readdir: out of memory");
    }
    struct dirent *ent;
    while ((ent = readdir(dir)) != NULL) {
        if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
            continue;
        if (len == cap) {
            cap *= 2;
            char **grown = realloc(names, cap * sizeof(*names));
            if (grown == NULL) {
                for (size_t i = 0; i < len; i++) free(names[i]);
                free(names);
                closedir(dir);
                return luaL_error(L, "readdir: out of memory");
            }
            names = grown;
        }
        names[len] = strdup(ent->d_name);
        if (names[len] == NULL) {
            for (size_t i = 0; i < len; i++) free(names[i]);
            free(names);
            closedir(dir);
            return luaL_error(L, "readdir: out of memory");
        }
        len++;
    }
    closedir(dir);
    qsort(names, len, sizeof(*names), fs_name_cmp);
    lua_createtable(L, (int)len, 0);
    for (size_t i = 0; i < len; i++) {
        lua_pushstring(L, names[i]);
        lua_rawseti(L, -2, (lua_Integer)i + 1);
        free(names[i]);
    }
    free(names);
    return 1;
}

/* tether.stat(path) -> { mtime, size, is_dir } | nil, err */
static int l_stat(lua_State *L)
{
    const char *path = luaL_checkstring(L, 1);
    struct stat st;
    if (lstat(path, &st) != 0) {
        lua_pushnil(L);
        lua_pushstring(L, strerror(errno));
        return 2;
    }
    lua_createtable(L, 0, 3);
    lua_pushinteger(L, (lua_Integer)st.st_mtime);
    lua_setfield(L, -2, "mtime");
    lua_pushinteger(L, (lua_Integer)st.st_size);
    lua_setfield(L, -2, "size");
    lua_pushboolean(L, S_ISDIR(st.st_mode) != 0);
    lua_setfield(L, -2, "is_dir");
    return 1;
}

/* --- krep recursive search --- */

/* Split one captured krep record ("path:lineno:text") in place.
   Returns 1 on success. The first ':' followed by a digit run and another ':'
   wins, which is the same rule the previous rg/grep parser used. */
static int krep_parse_line(char *line, char **path, long *lineno, char **text)
{
    for (char *c = line; (c = strchr(c, ':')) != NULL; c++) {
        char *digits = c + 1;
        if (!isdigit((unsigned char)*digits)) continue;
        char *end = digits;
        while (isdigit((unsigned char)*end)) end++;
        if (*end != ':') continue;
        *c = '\0';
        *end = '\0';
        *path = line;
        *lineno = strtol(digits, NULL, 10);
        *text = end + 1;
        return 1;
    }
    return 0;
}

/* tether.krep_search(base_dir, pattern, glob_filter, ignore_case,
 *                    use_gitignore, max_results)
 *   -> { {path, line, column, text}, ... } | nil, err
 *
 * krep's recursive search prints "path:lineno:line" records to stdout instead
 * of handing them back, so its output is captured through a temporary stream
 * and parsed. The printed form carries no column, so every record reports
 * column 1 (the tools spec allows that: "column is 1 when the engine omits
 * it"). With stdout not being a TTY, krep emits no ANSI color. */
static int l_krep_search(lua_State *L)
{
    const char *base_dir = luaL_checkstring(L, 1);
    const char *pattern = luaL_checkstring(L, 2);
    const char *glob_filter = luaL_optstring(L, 3, NULL);
    int ignore_case = lua_toboolean(L, 4);
    int use_gitignore = lua_toboolean(L, 5);
    lua_Integer max_results = luaL_optinteger(L, 6, 100);
    if (max_results < 0) max_results = 0;

    size_t pattern_len = strlen(pattern);
    search_params_t params;
    memset(&params, 0, sizeof(params));
    params.pattern = pattern;
    params.pattern_len = pattern_len;
    params.patterns = &pattern;
    params.pattern_lens = &pattern_len;
    params.num_patterns = 1;
    params.case_sensitive = ignore_case ? false : true;
    params.use_regex = true; /* POSIX ERE, matching the old tool default */
    params.track_positions = true;
    params.max_count = (max_results > 0) ? (size_t)max_results : SIZE_MAX;

    /* line numbers on so records carry a line; glob_filter is krep's --glob */
    krep_set_options(use_gitignore ? true : false, true, glob_filter);

    FILE *cap = tmpfile();
    if (cap == NULL) {
        lua_pushnil(L);
        lua_pushstring(L, "cannot create capture stream");
        return 2;
    }

    fflush(stdout);
    int saved_fd = dup(STDOUT_FILENO);
    if (saved_fd < 0 || dup2(fileno(cap), STDOUT_FILENO) < 0) {
        if (saved_fd >= 0) close(saved_fd);
        fclose(cap);
        lua_pushnil(L);
        lua_pushstring(L, "cannot capture krep output");
        return 2;
    }

    search_directory_recursive(base_dir, &params, 0);

    fflush(stdout);
    dup2(saved_fd, STDOUT_FILENO);
    close(saved_fd);

    /* slurp the capture */
    char *buf = NULL;
    if (fseek(cap, 0, SEEK_END) == 0) {
        long size = ftell(cap);
        if (size >= 0) {
            rewind(cap);
            buf = malloc((size_t)size + 1);
            if (buf != NULL) {
                size_t got = fread(buf, 1, (size_t)size, cap);
                buf[got] = '\0';
            }
        }
    }
    fclose(cap);
    if (buf == NULL)
        return luaL_error(L, "krep_search: cannot read captured output");

    lua_newtable(L);
    int count = 0;
    char *line = buf;
    while (line != NULL && *line != '\0') {
        if (max_results > 0 && count >= (int)max_results) break;
        char *nl = strchr(line, '\n');
        if (nl != NULL) *nl = '\0';
        char *path = NULL, *text = NULL;
        long lineno = 0;
        if (krep_parse_line(line, &path, &lineno, &text)) {
            lua_createtable(L, 0, 4);
            lua_pushstring(L, path);
            lua_setfield(L, -2, "path");
            lua_pushinteger(L, (lua_Integer)lineno);
            lua_setfield(L, -2, "line");
            lua_pushinteger(L, 1); /* krep's printed form omits the column */
            lua_setfield(L, -2, "column");
            lua_pushstring(L, text);
            lua_setfield(L, -2, "text");
            lua_rawseti(L, -2, ++count);
        }
        line = (nl != NULL) ? nl + 1 : NULL;
    }
    free(buf);
    return 1;
}

/* --- in-process HTTP(S) via vendor'd libcurl + mbedTLS + zlib --- */

/* The OS-distributed trust anchor; there is no per-call override and curl's
   own CURL_CA_BUNDLE handling is overridden by setting CAINFO explicitly. */
static const char *tether_ca_bundle(void)
{
    static const char *candidates[] = {
        "/etc/ssl/certs/ca-certificates.crt",
        "/etc/pki/tls/certs/ca-bundle.crt",
        "/etc/ssl/ca-bundle.pem",
    };
    for (size_t i = 0; i < sizeof(candidates) / sizeof(candidates[0]); i++) {
        if (access(candidates[i], R_OK) == 0)
            return candidates[i];
    }
    return NULL;
}

/* Read a whole file into a NUL-terminated buffer (caller frees). */
static int read_file_all(const char *path, char **out, size_t *outlen,
                         char *err, size_t errlen)
{
    FILE *f = fopen(path, "rb");
    if (f == NULL) {
        snprintf(err, errlen, "cannot open %s", path);
        return 0;
    }
    if (fseek(f, 0, SEEK_END) != 0) {
        fclose(f);
        snprintf(err, errlen, "cannot read %s", path);
        return 0;
    }
    long size = ftell(f);
    if (size < 0) {
        fclose(f);
        snprintf(err, errlen, "cannot read %s", path);
        return 0;
    }
    rewind(f);
    char *buf = malloc((size_t)size + 1);
    if (buf == NULL) {
        fclose(f);
        snprintf(err, errlen, "out of memory");
        return 0;
    }
    size_t got = fread(buf, 1, (size_t)size, f);
    fclose(f);
    buf[got] = '\0';
    *out = buf;
    *outlen = got;
    return 1;
}

/* Build a curl_slist from a Lua header array. A "@path" entry names a file
   whose non-empty lines are added as header lines (curl's -H @file), which is
   how the auth header temp file travels without the key entering argv. */
static struct curl_slist *http_build_headers(lua_State *L, int idx,
                                             char *err, size_t errlen)
{
    struct curl_slist *list = NULL;
    if (!lua_istable(L, idx))
        return NULL;
    int n = (int)lua_rawlen(L, idx);
    for (int i = 1; i <= n; i++) {
        lua_geti(L, idx, i);
        const char *entry = lua_tostring(L, -1);
        if (entry == NULL) {
            lua_pop(L, 1);
            continue;
        }
        if (entry[0] == '@') {
            FILE *f = fopen(entry + 1, "r");
            if (f == NULL) {
                snprintf(err, errlen, "cannot read header file");
                lua_pop(L, 1);
                curl_slist_free_all(list);
                return NULL;
            }
            char line[4096];
            while (fgets(line, sizeof(line), f) != NULL) {
                size_t len = strlen(line);
                while (len > 0 && (line[len - 1] == '\n' || line[len - 1] == '\r'))
                    line[--len] = '\0';
                if (len > 0)
                    list = curl_slist_append(list, line);
            }
            fclose(f);
        } else {
            list = curl_slist_append(list, entry);
        }
        lua_pop(L, 1);
    }
    return list;
}

/* Apply the options every request shares. Returns 1 on success. */
static int http_apply_common(CURL *h, const char *url, const char *ca,
                             struct curl_slist *headers)
{
    curl_easy_setopt(h, CURLOPT_URL, url);
    curl_easy_setopt(h, CURLOPT_CAINFO, ca);
    curl_easy_setopt(h, CURLOPT_SSL_VERIFYPEER, 1L);
    curl_easy_setopt(h, CURLOPT_SSL_VERIFYHOST, 2L);
    curl_easy_setopt(h, CURLOPT_FOLLOWLOCATION, 1L);
    curl_easy_setopt(h, CURLOPT_NOSIGNAL, 1L);
    curl_easy_setopt(h, CURLOPT_HTTPHEADER, headers);
    curl_easy_setopt(h, CURLOPT_USERAGENT, "tether");
    curl_easy_setopt(h, CURLOPT_ACCEPT_ENCODING, ""); /* gzip/deflate via zlib */
    return 1;
}

/* Streaming read callback: split the body into lines and hand each one to the
   Lua on_line function stored in the context. */
struct stream_ctx {
    lua_State *L;
    int fn_ref;
    char *buf;
    size_t len;
    size_t cap;
    int lua_error;
    char lua_err[256];
};

static int stream_emit_line(struct stream_ctx *ctx)
{
    lua_State *L = ctx->L;
    lua_rawgeti(L, LUA_REGISTRYINDEX, ctx->fn_ref);
    lua_pushlstring(L, ctx->buf ? ctx->buf : "", ctx->len);
    ctx->len = 0;
    if (lua_pcall(L, 1, 0, 0) != LUA_OK) {
        ctx->lua_error = 1;
        const char *msg = lua_tostring(L, -1);
        snprintf(ctx->lua_err, sizeof(ctx->lua_err), "%s", msg ? msg : "?");
        lua_pop(L, 1);
        return 0;
    }
    return 1;
}

static size_t http_write_cb(char *ptr, size_t size, size_t nmemb, void *userdata)
{
    struct stream_ctx *ctx = userdata;
    size_t total = size * nmemb;
    for (size_t i = 0; i < total; i++) {
        char c = ptr[i];
        if (c == '\n') {
            if (!stream_emit_line(ctx))
                return 0; /* abort the transfer */
            continue;
        }
        if (ctx->len + 1 >= ctx->cap) {
            size_t cap = ctx->cap ? ctx->cap * 2 : 4096;
            char *grown = realloc(ctx->buf, cap);
            if (grown == NULL)
                return 0;
            ctx->buf = grown;
            ctx->cap = cap;
        }
        ctx->buf[ctx->len++] = c;
    }
    return total;
}

/* Growable buffer for http_get. */
struct body_buf {
    char *data;
    size_t len;
    size_t cap;
};

static size_t http_body_cb(char *ptr, size_t size, size_t nmemb, void *userdata)
{
    struct body_buf *b = userdata;
    size_t total = size * nmemb;
    if (b->len + total + 1 > b->cap) {
        size_t cap = b->cap ? b->cap : 8192;
        while (cap < b->len + total + 1)
            cap *= 2;
        char *grown = realloc(b->data, cap);
        if (grown == NULL)
            return 0;
        b->data = grown;
        b->cap = cap;
    }
    memcpy(b->data + b->len, ptr, total);
    b->len += total;
    b->data[b->len] = '\0';
    return total;
}

/* Read the request body: a Lua string is used as-is, "@path" is read from a
   file (curl's --data-binary @file). */
static int http_read_body(const char *body, char **out, size_t *outlen,
                          char *err, size_t errlen)
{
    *out = NULL;
    *outlen = 0;
    if (body == NULL)
        return 1;
    if (body[0] == '@')
        return read_file_all(body + 1, out, outlen, err, errlen);
    *outlen = strlen(body);
    *out = malloc(*outlen + 1);
    if (*out == NULL) {
        snprintf(err, errlen, "out of memory");
        return 0;
    }
    memcpy(*out, body, *outlen + 1);
    return 1;
}

/* tether.http_stream(method, url, headers, body, on_line, opts) -> true | nil, err
 *
 * on_line(line) is called for every body line (the newline is not included).
 * opts: {timeout_s} connect timeout, default 10 s; {idle_timeout_s} max gap
 * between body bytes, default 60 s. There is deliberately no total timeout so
 * long SSE streams stay open. An HTTP error status is NOT a transport failure:
 * the body is still streamed so the caller can inspect the error JSON. */
static int l_http_stream(lua_State *L)
{
    const char *method = luaL_checkstring(L, 1);
    const char *url = luaL_checkstring(L, 2);
    const char *body = luaL_optstring(L, 4, NULL);
    luaL_checktype(L, 5, LUA_TFUNCTION);

    double connect_s = 10.0, idle_s = 60.0;
    if (lua_istable(L, 6)) {
        lua_getfield(L, 6, "timeout_s");
        if (lua_isnumber(L, -1)) connect_s = lua_tonumber(L, -1);
        lua_pop(L, 1);
        lua_getfield(L, 6, "connect_timeout_s");
        if (lua_isnumber(L, -1)) connect_s = lua_tonumber(L, -1);
        lua_pop(L, 1);
        lua_getfield(L, 6, "idle_timeout_s");
        if (lua_isnumber(L, -1)) idle_s = lua_tonumber(L, -1);
        lua_pop(L, 1);
    }

    const char *ca = tether_ca_bundle();
    if (ca == NULL) {
        lua_pushnil(L);
        lua_pushstring(L, "no system CA bundle found");
        return 2;
    }

    char err[256] = {0};
    struct curl_slist *headers = http_build_headers(L, 3, err, sizeof(err));
    if (err[0] != '\0') {
        lua_pushnil(L);
        lua_pushstring(L, err);
        return 2;
    }

    char *body_buf = NULL;
    size_t body_len = 0;
    if (!http_read_body(body, &body_buf, &body_len, err, sizeof(err))) {
        curl_slist_free_all(headers);
        lua_pushnil(L);
        lua_pushstring(L, err);
        return 2;
    }

    CURL *h = curl_easy_init();
    if (h == NULL) {
        curl_slist_free_all(headers);
        free(body_buf);
        lua_pushnil(L);
        lua_pushstring(L, "cannot create HTTP handle");
        return 2;
    }

    struct stream_ctx ctx;
    memset(&ctx, 0, sizeof(ctx));
    ctx.L = L;
    lua_pushvalue(L, 5);
    ctx.fn_ref = luaL_ref(L, LUA_REGISTRYINDEX);

    http_apply_common(h, url, ca, headers);
    curl_easy_setopt(h, CURLOPT_CONNECTTIMEOUT_MS, (long)(connect_s * 1000.0));
    /* libcurl has no native idle timeout; the low-speed limit aborts when the
       transfer stays under 1 byte/s for idle_s seconds. */
    curl_easy_setopt(h, CURLOPT_LOW_SPEED_LIMIT, 1L);
    curl_easy_setopt(h, CURLOPT_LOW_SPEED_TIME, (long)idle_s);
    curl_easy_setopt(h, CURLOPT_WRITEFUNCTION, http_write_cb);
    curl_easy_setopt(h, CURLOPT_WRITEDATA, &ctx);
    /* Ctrl+C during a transfer: libcurl calls this between packets, so the
       turn ends promptly instead of when the provider's stream happens to end. */
    curl_easy_setopt(h, CURLOPT_NOPROGRESS, 0L);
    curl_easy_setopt(h, CURLOPT_XFERINFOFUNCTION, http_xferinfo);
    curl_easy_setopt(h, CURLOPT_XFERINFODATA, NULL);
    if (body_buf != NULL) {
        curl_easy_setopt(h, CURLOPT_POSTFIELDS, body_buf);
        curl_easy_setopt(h, CURLOPT_POSTFIELDSIZE, (long)body_len);
    }
    if (method[0] != '\0' && strcasecmp(method, "POST") != 0)
        curl_easy_setopt(h, CURLOPT_CUSTOMREQUEST, method);

    CURLcode rc = curl_easy_perform(h);

    /* a final line without a trailing newline still counts */
    if (rc == CURLE_OK && ctx.len > 0 && !ctx.lua_error)
        stream_emit_line(&ctx);

    luaL_unref(L, LUA_REGISTRYINDEX, ctx.fn_ref);
    curl_slist_free_all(headers);
    curl_easy_cleanup(h);
    free(body_buf);
    free(ctx.buf);

    if (ctx.lua_error) {
        lua_pushnil(L);
        lua_pushstring(L, ctx.lua_err);
        return 2;
    }
    if (rc != CURLE_OK) {
        lua_pushnil(L);
        lua_pushstring(L, curl_easy_strerror(rc));
        return 2;
    }
    lua_pushboolean(L, 1);
    return 1;
}

/* tether.http_get(url, headers, timeout_s) -> body | nil, err
 *
 * timeout_s is the total request timeout in seconds (default 30). A status of
 * 400 or above is reported as nil, "http <status>" rather than as a body. */
static int l_http_get(lua_State *L)
{
    const char *url = luaL_checkstring(L, 1);
    double timeout_s = 30.0;
    if (lua_isnumber(L, 3))
        timeout_s = lua_tonumber(L, 3);

    const char *ca = tether_ca_bundle();
    if (ca == NULL) {
        lua_pushnil(L);
        lua_pushstring(L, "no system CA bundle found");
        return 2;
    }

    char err[256] = {0};
    struct curl_slist *headers = http_build_headers(L, 2, err, sizeof(err));
    if (err[0] != '\0') {
        lua_pushnil(L);
        lua_pushstring(L, err);
        return 2;
    }

    CURL *h = curl_easy_init();
    if (h == NULL) {
        curl_slist_free_all(headers);
        lua_pushnil(L);
        lua_pushstring(L, "cannot create HTTP handle");
        return 2;
    }

    struct body_buf body;
    memset(&body, 0, sizeof(body));

    http_apply_common(h, url, ca, headers);
    curl_easy_setopt(h, CURLOPT_HTTPGET, 1L);
    curl_easy_setopt(h, CURLOPT_TIMEOUT_MS, (long)(timeout_s * 1000.0));
    curl_easy_setopt(h, CURLOPT_WRITEFUNCTION, http_body_cb);
    curl_easy_setopt(h, CURLOPT_WRITEDATA, &body);

    CURLcode rc = curl_easy_perform(h);
    long status = 0;
    curl_easy_getinfo(h, CURLINFO_RESPONSE_CODE, &status);
    curl_slist_free_all(headers);
    curl_easy_cleanup(h);

    if (rc != CURLE_OK) {
        free(body.data);
        lua_pushnil(L);
        lua_pushstring(L, curl_easy_strerror(rc));
        return 2;
    }
    if (status >= 400) {
        free(body.data);
        char msg[64];
        snprintf(msg, sizeof(msg), "http %ld", status);
        lua_pushnil(L);
        lua_pushstring(L, msg);
        return 2;
    }
    lua_pushlstring(L, body.data ? body.data : "", body.len);
    free(body.data);
    return 1;
}

static int l_resize_requested(lua_State *L)
{
    lua_pushboolean(L, g_resize_requested);
    g_resize_requested = 0;
    return 1;
}

/* T15: sleep — used by API retry backoff. add-retry-and-continuation: the wait
   wakes as soon as input arrives (a Ctrl+C during a backoff ends the wait
   instead of being read only after the turn it was meant to interrupt), and it
   still lasts its requested duration when nothing arrives. */
static int l_sleep(lua_State *L)
{
    double secs = luaL_optnumber(L, 1, 0.0);
    if (secs <= 0.0) return 0;
    if (g_stdin_eof) {
        /* nothing to watch: a poll on a closed stdin would return at once */
        long us = (long)(secs * 1000000);
        struct timespec ts;
        ts.tv_sec = us / 1000000;
        ts.tv_nsec = (us % 1000000) * 1000L;
        nanosleep(&ts, NULL);
        return 0;
    }
    struct timespec start, now;
    clock_gettime(CLOCK_MONOTONIC, &start);
    for (;;) {
        if (poll_interrupt()) return 0; /* interrupted: end the wait now */
        clock_gettime(CLOCK_MONOTONIC, &now);
        double elapsed = (double)(now.tv_sec - start.tv_sec)
            + (double)(now.tv_nsec - start.tv_nsec) / 1e9;
        double remaining = secs - elapsed;
        if (remaining <= 0.0) break;
        int ms = (int)(remaining * 1000.0);
        if (ms > 200) ms = 200; /* bounded: re-check the flag at least every 200ms */
        struct pollfd pfd;
        pfd.fd = STDIN_FILENO;
        pfd.events = POLLIN;
        pfd.revents = 0;
        poll(&pfd, 1, ms); /* returns early when the user types */
    }
    return 0;
}

/* add-retry-and-continuation: does the user want this turn stopped? The flag
   stays set until clear_abort(), because the very same Ctrl+C has to keep
   aborting an in-flight transfer (http_xferinfo) until the turn has actually
   stopped — only the turn knows when that happened. */
static int l_abort_requested(lua_State *L)
{
    poll_interrupt();
    lua_pushboolean(L, g_interrupt != 0);
    return 1;
}

/* Drop a stale interrupt when a turn starts. */
static int l_clear_abort(lua_State *L)
{
    (void)L;
    g_interrupt = 0;
    return 0;
}

static int l_detect_kb_protocol(lua_State *L)
{
    const char *tp = getenv("TERM_PROGRAM");
    const char *tm = getenv("TERM");
    if (tp && (strstr(tp, "kitty") || strstr(tp, "Kitty"))) {
        lua_pushinteger(L, 1); /* kitty */
        return 1;
    }
    if ((tp && (strstr(tp, "VTE") || strstr(tp, "alacritty") || strstr(tp, "gnome"))) ||
        (tm && (strstr(tm, "xterm") || strstr(tm, "vte") || strstr(tm, "gnome")))) {
        lua_pushinteger(L, 2); /* modifyOtherKeys */
        return 1;
    }
    lua_pushinteger(L, 0); /* plain */
    return 1;
}

static luaL_Reg tether_api[] = {
    {"read_char",       l_read_char},
    {"read_char_nb",    l_read_char_nb},
    {"write",           l_write},
    {"exec",        l_exec},
    {"realpath",    l_realpath},
    {"getcwd",      l_getcwd},
    {"is_tty",      l_tty},
    {"get_terminal_size", l_get_terminal_size},
    {"mkdirp",      l_mkdirp},
    {"fchmod",      l_fchmod},
    {"readdir",     l_readdir},
    {"stat",        l_stat},
    {"krep_search", l_krep_search},
    {"http_stream", l_http_stream},
    {"http_get",    l_http_get},
    {"resize_requested", l_resize_requested},
    {"sleep",         l_sleep},
    {"abort_requested", l_abort_requested},
    {"clear_abort",   l_clear_abort},
    {"detect_kb_protocol", l_detect_kb_protocol},
    {NULL, NULL}
};

static void open_tether_api(lua_State *L)
{
    /* idempotent; needed before any libcurl use (TLS backend init, zlib) */
    curl_global_init(CURL_GLOBAL_DEFAULT);
    luaL_newlib(L, tether_api);
    lua_setglobal(L, "tether");
}

/* Load a Lua chunk, execute it, store its single return value in global `name`. */
static int load_module(lua_State *L, const char *src, const char *name)
{
    int lr = luaL_loadstring(L, src);
    if (lr != LUA_OK) {
        fprintf(stderr, "tether: load %s: %s\n", name, lua_tostring(L, -1));
        lua_pop(L, 1);
        return 1;
    }
    lr = lua_pcall(L, 0, 1, 0);
    if (lr != LUA_OK) {
        fprintf(stderr, "tether: run %s: %s\n", name, lua_tostring(L, -1));
        lua_pop(L, 1);
        return 1;
    }
    if (lua_isnil(L, -1)) {
        lua_pop(L, 1);
        lua_newtable(L);
    }
    lua_setglobal(L, name);
    return 0;
}

int main(int argc, char **argv)
{
    int interactive = isatty(STDIN_FILENO) == 1;

    /* Install signal handling in every mode: SIGINT/SIGTERM restore the
       terminal (no-op when raw mode was never enabled) and exit cleanly.
       SIGWINCH only matters for the TUI. */
    setup_signal_handlers();

    if (interactive) {
        if (init_termios() != 0) {
            perror("tcsetattr");
            return 1;
        }
        atexit(restore_termios);
    }

    lua_State *L = luaL_newstate();
    if (!L) {
        fprintf(stderr, "tether: cannot allocate lua state\n");
        restore_termios();
        return 1;
    }
    luaL_openlibs(L);
    open_tether_api(L);

    int rc = 0;
    struct { const char *src; const char *name; } mods[] = {
        /* provider_common first: session/agent resolve their JSON helpers to it */
        { provider_common_lua,    "provider_common"    },
        /* retry: pure policy module api/agent apply (see src/tether/retry.lua) */
        { retry_lua,   "retry"   },
        { session_lua, "session" },
        { diff_lua,   "diff"   },
        /* ask: the structured-question rules ui/agent apply (src/tether/ask.lua) */
        { ask_lua,    "ask"    },
        /* confirm_policy: pure should_confirm/approve_key policy (src/tether/confirm_policy.lua) */
        { confirm_policy_lua, "confirm_policy" },
        /* auth: OAuth/API-key store for /login /logout (src/tether/auth.lua) */
        { auth_lua, "auth" },
        /* transcript: visible conversation model; ui loads it before State */
        { transcript_lua, "transcript" },
        /* commands: session lifecycle + slash side effects (src/tether/commands.lua) */
        { commands_lua, "commands" },
        /* turn: control facade over agent; abort seam + busy reset (src/tether/turn.lua) */
        { turn_lua, "turn" },
        { ui_lua,     "ui"     },
        { config_lua, "config" },
        { tools_lua,  "tools"  },
        { provider_openai_lua,    "provider_openai"    },
        { provider_anthropic_lua, "provider_anthropic" },
        { provider_gemini_lua,    "provider_gemini"    },
        { api_lua,    "api"    },
        { context_lua, "context" },
        { agent_lua,  "agent"  },
        { app_lua,    "app"    },
    };
    for (size_t i = 0; i < sizeof(mods)/sizeof(mods[0]); i++) {
        if (load_module(L, mods[i].src, mods[i].name) != 0) { rc = 1; break; }
    }
    if (rc == 0) {
        /* Push argv to Lua 'arg' global for CLI parsing */
        lua_newtable(L);
        for (int i = 1; i < argc; i++) {
            lua_pushstring(L, argv[i]);
            lua_rawseti(L, -2, i);
        }
        lua_setglobal(L, "arg");
        lua_getglobal(L, "app");
        lua_getfield(L, -1, "run");
        int rc2 = lua_pcall(L, 0, 0, 0);
        if (rc2 != LUA_OK) {
            fprintf(stderr, "tether: app.run: %s\n", lua_tostring(L, -1));
            lua_pop(L, 1);
            rc = 1;
        }
        lua_pop(L, 1);
    }

    lua_close(L);
    restore_termios();
    return rc == 0 ? 0 : 1;
}
