/* tether M2: C host — Lua 5.4.6 embedded, raw-mode terminal, tether API */
#define _XOPEN_SOURCE 500
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <sys/select.h>
#include <termios.h>
#include <sys/ioctl.h>
#include <limits.h>
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

/* embedded Lua sources (generated by tools/embed.lua) */
#include "embed.c"

static struct termios orig_termios;
static int termios_active = 0;

static void restore_termios(void)
{
    if (termios_active) {
        tcsetattr(STDIN_FILENO, TCSANOW, &orig_termios);
        printf("\x1b[?25h\n");
        fflush(stdout);
        termios_active = 0;
    }
}

static volatile sig_atomic_t g_resize_requested = 0;

/* SIGTERM/SIGINT: restore the terminal (a no-op when raw mode was never
   enabled) and exit cleanly. Raw mode disables ISIG, so an in-terminal
   Ctrl+C arrives as byte 0x03 and only an external signal lands here. */
static void on_exit_signal(int sig)
{
    (void)sig;
    restore_termios();
    _exit(0);
}

static void on_sigwinch(int sig)
{
    (void)sig;
    g_resize_requested = 1;
}

static void setup_signal_handlers(void)
{
    struct sigaction sa_term, sa_winch;
    sa_term.sa_handler = on_exit_signal;
    sigemptyset(&sa_term.sa_mask);
    sa_term.sa_flags = 0;
    sigaction(SIGTERM, &sa_term, NULL);
    sigaction(SIGINT, &sa_term, NULL);
    sa_winch.sa_handler = on_sigwinch;
    sigemptyset(&sa_winch.sa_mask);
    sa_winch.sa_flags = SA_RESTART;
    sigaction(SIGWINCH, &sa_winch, NULL);
}

static int init_termios(void)
{
    struct termios raw;
    if (tcgetattr(STDIN_FILENO, &orig_termios) == -1)
        return -1;
    raw = orig_termios;
    raw.c_iflag &= ~(BRKINT | ICRNL | INPCK | ISTRIP | IXON);
    /* OPOST kept enabled: \n -> \r\n translation for proper line rendering */
    raw.c_cflag |= CS8;
    raw.c_lflag &= ~(ECHO | ICANON | ISIG | IEXTEN);
    raw.c_cc[VMIN] = 1;
    raw.c_cc[VTIME] = 0;
    if (tcsetattr(STDIN_FILENO, TCSANOW, &raw) == -1)
        return -1;
    termios_active = 1;
    return 0;
}

/* --- tether.* API exposed to Lua --- */

static int l_read_char(lua_State *L)
{
    char c;
    ssize_t n = read(STDIN_FILENO, &c, 1);
    if (n != 1)
        lua_pushnil(L);
    else
        lua_pushinteger(L, (unsigned char)c);
    return 1;
}

static int l_read_char_nb(lua_State *L)
{
    fd_set fds;
    struct timeval tv;
    FD_ZERO(&fds);
    FD_SET(STDIN_FILENO, &fds);
    tv.tv_sec = 0;
    tv.tv_usec = 50000;
    int ready = select(STDIN_FILENO + 1, &fds, NULL, NULL, &tv);
    if (ready <= 0) { lua_pushnil(L); return 1; }
    char c;
    ssize_t n = read(STDIN_FILENO, &c, 1);
    if (n != 1)
        lua_pushnil(L);
    else
        lua_pushinteger(L, (unsigned char)c);
    return 1;
}

static int l_write(lua_State *L)
{
    size_t len;
    const char *s = luaL_checklstring(L, 1, &len);
    ssize_t w = write(STDOUT_FILENO, s, len);
    if (w == -1)
        luaL_error(L, "write: %s", strerror(errno));
    if (w != (ssize_t)len) {
        /* partial write: retry remaining bytes */
        const char *ptr = s + w;
        size_t remaining = len - w;
        while (remaining > 0) {
            w = write(STDOUT_FILENO, ptr, remaining);
            if (w == -1) break;
            ptr += w;
            remaining -= w;
        }
    }
    fflush(stdout);
    return 0;
}

static int l_exec(lua_State *L)
{
    const char *cmd = luaL_checkstring(L, 1);
    /* system() already runs via sh -c, so pass cmd directly */
    int code = system(cmd);
    int exit_code = WEXITSTATUS(code);
    lua_pushboolean(L, exit_code == 0);
    lua_pushinteger(L, exit_code);
    return 2;
}

static int l_realpath(lua_State *L)
{
    const char *path = luaL_checkstring(L, 1);
    char resolved[PATH_MAX];
    char *rp = realpath(path, resolved);
    if (rp == NULL) {
        lua_pushboolean(L, 0);
        return 1;
    }
    lua_pushstring(L, rp);
    return 1;
}

static int l_getcwd(lua_State *L)
{
    char buf[4096];
    if (getcwd(buf, sizeof(buf)) == NULL)
        luaL_error(L, "getcwd: %s", strerror(errno));
    lua_pushstring(L, buf);
    return 1;
}

static int l_get_terminal_size(lua_State *L)
{
    struct winsize ws;
    if (ioctl(STDIN_FILENO, TIOCGWINSZ, &ws) == 0) {
        lua_newtable(L);
        lua_pushinteger(L, ws.ws_col);
        lua_setfield(L, -2, "width");
        lua_pushinteger(L, ws.ws_row);
        lua_setfield(L, -2, "height");
    } else {
        lua_pushnil(L);
    }
    return 1;
}

static int l_tty(lua_State *L)
{
    lua_pushboolean(L, isatty(STDIN_FILENO) == 1);
    return 1;
}

/* --- pipe API for SSE streaming --- */

#include <sys/wait.h>
#include <poll.h>

struct pipe_state {
    int fd;
    int child;
    int eof;
    char buf[8192];
    size_t buf_len;
    size_t buf_pos;
    char *line;        /* accumulator: SSE lines can exceed any fixed buffer */
    size_t line_len;
    size_t line_cap;
};
static struct pipe_state g_pipe;

static void pipe_line_reset(void)
{
    free(g_pipe.line);
    g_pipe.line = NULL;
    g_pipe.line_len = 0;
    g_pipe.line_cap = 0;
}

/* append one byte to the line accumulator; NULL on OOM (drops the line) */
static int pipe_line_put(char c)
{
    if (g_pipe.line_len + 1 >= g_pipe.line_cap) {
        size_t cap = g_pipe.line_cap ? g_pipe.line_cap * 2 : 8192;
        char *grown = realloc(g_pipe.line, cap);
        if (!grown) return 0;
        g_pipe.line = grown;
        g_pipe.line_cap = cap;
    }
    g_pipe.line[g_pipe.line_len++] = c;
    return 1;
}

/* tether.open_pipe(cmd) -> handle | err */
static int l_open_pipe(lua_State *L)
{
    const char *cmd = luaL_checkstring(L, 1);
    int fds[2];
    if (pipe(fds) != 0) {
        luaL_error(L, "pipe: %s", strerror(errno));
    }
    pid_t pid = fork();
    if (pid == 0) {
        /* child */
        close(fds[0]);
        dup2(fds[1], STDOUT_FILENO);
        dup2(fds[1], STDERR_FILENO);
        close(fds[1]);
        execl("/bin/sh", "sh", "-c", cmd, (char *)NULL);
        _exit(127);
    } else if (pid > 0) {
        close(fds[1]);
        g_pipe.fd = fds[0];
        g_pipe.child = pid;
        g_pipe.eof = 0;
        g_pipe.buf_len = 0;
        g_pipe.buf_pos = 0;
        pipe_line_reset();
        lua_pushinteger(L, 1); /* handle */
        return 1;
    } else {
        close(fds[0]); close(fds[1]);
        luaL_error(L, "fork: %s", strerror(errno));
    }
    return 0;
}

/* tether.read_line(handle) -> line | nil  (blocks) */
static int l_read_line(lua_State *L)
{
    if (g_pipe.eof) { lua_pushnil(L); return 1; }
    pipe_line_reset();
    while (1) {
        char c;
        if (g_pipe.buf_pos < g_pipe.buf_len) {
            c = g_pipe.buf[g_pipe.buf_pos++];
        } else {
            ssize_t n = read(g_pipe.fd, &c, 1);
            if (n == 0) { g_pipe.eof = 1; break; }
            if (n < 0 && errno != EINTR) { g_pipe.eof = 1; break; }
            if (n < 0) continue; /* EINTR */
        }
        if (c == '\n') break;
        if (!pipe_line_put(c)) { g_pipe.eof = 1; break; } /* OOM: drop and report */
    }
    /* an empty line ("\n") must surface as "" — SSE event separators are
       valid mid-stream; nil is reserved for real EOF (read() == 0) */
    lua_pushlstring(L, g_pipe.line ? g_pipe.line : "", g_pipe.line_len);
    return 1;
}

/* tether.close_pipe() */
static int l_close_pipe(lua_State *L)
{
    (void)L;
    if (g_pipe.fd >= 0) { close(g_pipe.fd); g_pipe.fd = -1; }
    if (g_pipe.child > 0) { waitpid(g_pipe.child, NULL, 0); g_pipe.child = 0; }
    g_pipe.eof = 0;
    pipe_line_reset();
    return 0;
}

static int l_pipe_eof(lua_State *L)
{
    lua_pushboolean(L, g_pipe.eof);
    return 1;
}

static int l_resize_requested(lua_State *L)
{
    lua_pushboolean(L, g_resize_requested);
    g_resize_requested = 0;
    return 1;
}

/* T15: sleep — used by API retry backoff */
#include <time.h>

static int l_sleep(lua_State *L)
{
    double secs = luaL_optnumber(L, 1, 0.0);
    if (secs <= 0.0) return 0;
    long us = (long)(secs * 1000000);
    struct timespec ts;
    ts.tv_sec = us / 1000000;
    ts.tv_nsec = (us % 1000000) * 1000L;
    nanosleep(&ts, NULL);
    return 0;
}

static int l_detect_kb_protocol(lua_State *L)
{
    const char *tp = getenv("TERM_PROGRAM");
    const char *tm = getenv("TERM");
    if (tp && (strstr(tp, "kitty") || strstr(tp, "Kitty"))) {
        lua_pushinteger(L, 1); /* kitty */
        return 1;
    }
    if ((tp && (strstr(tp, "VTE") || strstr(tp, "alacritty") || strstr(tp, "gnome"))) ||
        (tm && (strstr(tm, "xterm") || strstr(tm, "vte") || strstr(tm, "gnome")))) {
        lua_pushinteger(L, 2); /* modifyOtherKeys */
        return 1;
    }
    lua_pushinteger(L, 0); /* plain */
    return 1;
}

static luaL_Reg tether_api[] = {
    {"read_char",       l_read_char},
    {"read_char_nb",    l_read_char_nb},
    {"write",           l_write},
    {"exec",        l_exec},
    {"realpath",    l_realpath},
    {"getcwd",      l_getcwd},
    {"is_tty",      l_tty},
    {"get_terminal_size", l_get_terminal_size},
    {"open_pipe",   l_open_pipe},
    {"read_line",   l_read_line},
    {"close_pipe",  l_close_pipe},
    {"pipe_eof",    l_pipe_eof},
    {"resize_requested", l_resize_requested},
    {"sleep",         l_sleep},
    {"detect_kb_protocol", l_detect_kb_protocol},
    {NULL, NULL}
};

static void open_tether_api(lua_State *L)
{
    luaL_newlib(L, tether_api);
    lua_setglobal(L, "tether");
}

/* Load a Lua chunk, execute it, store its single return value in global `name`. */
static int load_module(lua_State *L, const char *src, const char *name)
{
    int lr = luaL_loadstring(L, src);
    if (lr != LUA_OK) {
        fprintf(stderr, "tether: load %s: %s\n", name, lua_tostring(L, -1));
        lua_pop(L, 1);
        return 1;
    }
    lr = lua_pcall(L, 0, 1, 0);
    if (lr != LUA_OK) {
        fprintf(stderr, "tether: run %s: %s\n", name, lua_tostring(L, -1));
        lua_pop(L, 1);
        return 1;
    }
    if (lua_isnil(L, -1)) {
        lua_pop(L, 1);
        lua_newtable(L);
    }
    lua_setglobal(L, name);
    return 0;
}

int main(int argc, char **argv)
{
    g_pipe.fd = -1;
    g_pipe.child = 0;
    g_pipe.eof = 1;
    int interactive = isatty(STDIN_FILENO) == 1;

    /* Install signal handling in every mode: SIGINT/SIGTERM restore the
       terminal (no-op when raw mode was never enabled) and exit cleanly.
       SIGWINCH only matters for the TUI. */
    setup_signal_handlers();

    if (interactive) {
        if (init_termios() != 0) {
            perror("tcsetattr");
            return 1;
        }
        atexit(restore_termios);
    }

    lua_State *L = luaL_newstate();
    if (!L) {
        fprintf(stderr, "tether: cannot allocate lua state\n");
        restore_termios();
        return 1;
    }
    luaL_openlibs(L);
    open_tether_api(L);

    int rc = 0;
    struct { const char *src; const char *name; } mods[] = {
        /* provider_common first: session/agent resolve their JSON helpers to it */
        { provider_common_lua,    "provider_common"    },
        { session_lua, "session" },
        { ui_lua,     "ui"     },
        { config_lua, "config" },
        { tools_lua,  "tools"  },
        { provider_openai_lua,    "provider_openai"    },
        { provider_anthropic_lua, "provider_anthropic" },
        { provider_gemini_lua,    "provider_gemini"    },
        { api_lua,    "api"    },
        { context_lua, "context" },
        { agent_lua,  "agent"  },
        { app_lua,    "app"    },
    };
    for (size_t i = 0; i < sizeof(mods)/sizeof(mods[0]); i++) {
        if (load_module(L, mods[i].src, mods[i].name) != 0) { rc = 1; break; }
    }
    if (rc == 0) {
        /* Push argv to Lua 'arg' global for CLI parsing */
        lua_newtable(L);
        for (int i = 1; i < argc; i++) {
            lua_pushstring(L, argv[i]);
            lua_rawseti(L, -2, i);
        }
        lua_setglobal(L, "arg");
        lua_getglobal(L, "app");
        lua_getfield(L, -1, "run");
        int rc2 = lua_pcall(L, 0, 0, 0);
        if (rc2 != LUA_OK) {
            fprintf(stderr, "tether: app.run: %s\n", lua_tostring(L, -1));
            lua_pop(L, 1);
            rc = 1;
        }
        lua_pop(L, 1);
    }

    lua_close(L);
    restore_termios();
    return rc == 0 ? 0 : 1;
}
