/* tether M2: C host — Lua 5.4.6 embedded, raw-mode terminal, tether API */
#define _XOPEN_SOURCE 500
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <sys/select.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h> /* WEXITSTATUS in l_exec */
#include <dirent.h>
#include <fcntl.h>
#include <termios.h>
#include <sys/ioctl.h>
#include <limits.h>
#include <strings.h>
#include <poll.h>
#include <time.h>
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#include <curl/curl.h>
#include <mbedtls/pk.h>
#include <mbedtls/sha256.h>
#include <mbedtls/md.h>

/* Vendor'd krep engine (grep backend). Its header also defines file-scope
   skip lists that only krep.c itself consumes; silence the unused-variable
   warnings those would otherwise raise here under -Werror. */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-const-variable"
#include "krep.h"
#pragma GCC diagnostic pop

/* embedded Lua sources (generated by tools/embed.lua) */
#include "embed.c"

static struct termios orig_termios;
static int termios_active = 0;

/* --- Ctrl+C while a turn blocks -------------------------------------------
   Raw mode clears ISIG, so an in-terminal Ctrl+C arrives as byte 0x03 rather
   than SIGINT, and the UI reads input only between turns — exactly when no turn
   is running. While a turn blocks (tether.sleep, an in-flight HTTP transfer)
   the host therefore watches stdin itself: 0x03 raises `g_interrupt`, and every
   other byte is queued so read_char still delivers it. That way a Ctrl+C can
   stop the turn it was meant for, without losing a keystroke. */
#define PENDING_CAP 256
static unsigned char g_pending[PENDING_CAP];
static size_t g_pending_len = 0; /* bytes queued */
static size_t g_pending_pos = 0; /* bytes handed back */
static int g_interrupt = 0;
static int g_stdin_eof = 0; /* stop watching once input is exhausted */

/* Take one queued byte, if any. */
static int pending_take(unsigned char *out)
{
    if (g_pending_pos >= g_pending_len) {
        g_pending_len = g_pending_pos = 0;
        return 0;
    }
    *out = g_pending[g_pending_pos++];
    return 1;
}

/* Non-blocking: queue every available byte, remember a Ctrl+C. Returns non-zero
   when an interrupt is pending. Never blocks and never delays a caller. */
static int poll_interrupt(void)
{
    if (g_stdin_eof) return g_interrupt;
    for (;;) {
        struct pollfd pfd;
        pfd.fd = STDIN_FILENO;
        pfd.events = POLLIN;
        pfd.revents = 0;
        int rc = poll(&pfd, 1, 0);
        if (rc <= 0) break;
        unsigned char buf[64];
        ssize_t n = read(STDIN_FILENO, buf, sizeof buf);
        if (n <= 0) {
            if (n == 0) g_stdin_eof = 1; /* pipes: nothing more will arrive */
            else if (errno != EINTR && errno != EAGAIN) g_stdin_eof = 1;
            break;
        }
        for (ssize_t i = 0; i < n; i++) {
            if (buf[i] == 3) {
                g_interrupt = 1;
            } else if (g_pending_len - g_pending_pos < PENDING_CAP) {
                g_pending[g_pending_len++] = buf[i];
            }
        }
    }
    return g_interrupt;
}

/* Busy-spinner tick: repaints the ` Working...` indicator while a turn runs.
   The registered hook is a no-op unless a turn is busy. Throttled to the
   spinner interval (80 ms, pi's Loader default); re-entrancy guarded because
   the tick runs a full repaint from inside the transfer.

   The hook is bound explicitly (tether.set_tick_hook) instead of read from a
   magic global name: only ui.run registers it, so print mode and plain tests
   stay silent, and the blocking waits that still need it (tether.exec,
   http_get, the blocking http_stream/sleep fallbacks) call the one function
   the TUI handed over. */
#define SPINNER_QUANTUM_MS 80
static int g_tick_hook_ref = LUA_NOREF;

/* tether.set_tick_hook(fn | nil): register the UI tick the blocking waits
   may call back into. nil (or a non-function) unregisters it. */
static int l_set_tick_hook(lua_State *L)
{
    if (g_tick_hook_ref != LUA_NOREF) {
        luaL_unref(L, LUA_REGISTRYINDEX, g_tick_hook_ref);
        g_tick_hook_ref = LUA_NOREF;
    }
    if (lua_isfunction(L, 1)) {
        lua_pushvalue(L, 1);
        g_tick_hook_ref = luaL_ref(L, LUA_REGISTRYINDEX);
    }
    return 0;
}

static double spinner_tick_now_ms(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (double)ts.tv_sec * 1000.0 + (double)ts.tv_nsec / 1e6;
}

static void spinner_tick_call(lua_State *L)
{
    if (L == NULL || g_tick_hook_ref == LUA_NOREF) return;
    static double last_tick_ms = 0;
    static int in_tick = 0;
    double now = spinner_tick_now_ms();
    if (in_tick || now - last_tick_ms < (double)SPINNER_QUANTUM_MS) return;
    last_tick_ms = now;
    in_tick = 1;
    lua_rawgeti(L, LUA_REGISTRYINDEX, g_tick_hook_ref);
    if (lua_pcall(L, 0, 0, 0) != LUA_OK)
        lua_pop(L, 1);
    in_tick = 0;
}

/* libcurl progress callback: abort an in-flight transfer as soon as Ctrl+C
   arrives, so a stalled stream cannot hold the turn. Also fires the spinner
   tick on network activity (the multi-loop quantum below covers silence). */
static int http_xferinfo(void *clientp, curl_off_t dltotal, curl_off_t dlnow,
                         curl_off_t ultotal, curl_off_t ulnow)
{
    (void)dltotal; (void)dlnow; (void)ultotal; (void)ulnow;
    if (poll_interrupt()) return 1;
    spinner_tick_call((lua_State *)clientp);
    return 0;
}

/* Run a streaming transfer on a multi handle with an 80 ms poll quantum.
   curl_easy_perform blocks Lua for the whole SSE stream and only invokes the
   progress callback on network activity, so a tick from xferinfo alone fires
   at libcurl's mercy: frozen TTFT, choppy animation. The multi loop wakes on
   socket activity AND on quantum timeout, so the spinner animates at a steady
   rate for the whole transfer while Ctrl+C still aborts promptly. */
static CURLcode stream_perform(CURL *h, lua_State *L)
{
    CURLM *m = curl_multi_init();
    if (m == NULL) return CURLE_OUT_OF_MEMORY;
    if (curl_multi_add_handle(m, h) != CURLM_OK) {
        curl_multi_cleanup(m);
        return CURLE_FAILED_INIT;
    }
    CURLcode rc = CURLE_OK;
    int still_running = 0;
    if (curl_multi_perform(m, &still_running) != CURLM_OK)
        still_running = 0;
    while (still_running) {
        int numfds = 0;
        if (curl_multi_poll(m, NULL, 0, SPINNER_QUANTUM_MS, &numfds) != CURLM_OK)
            break;
        if (poll_interrupt()) { rc = CURLE_ABORTED_BY_CALLBACK; break; }
        spinner_tick_call(L);
        if (curl_multi_perform(m, &still_running) != CURLM_OK)
            break;
    }
    if (rc == CURLE_OK) {
        CURLMsg *msg;
        int left = 0;
        while ((msg = curl_multi_info_read(m, &left)) != NULL) {
            if (msg->msg == CURLMSG_DONE && msg->easy_handle == h)
                rc = msg->data.result;
        }
    }
    curl_multi_remove_handle(m, h);
    curl_multi_cleanup(m);
    return rc;
}

static void restore_termios(void)
{
    if (termios_active) {
        tcsetattr(STDIN_FILENO, TCSANOW, &orig_termios);
        printf("\x1b[?25h\n");
        fflush(stdout);
        termios_active = 0;
    }
}

static volatile sig_atomic_t g_resize_requested = 0;

/* SIGTERM/SIGINT: restore the terminal (a no-op when raw mode was never
   enabled) and exit cleanly. Raw mode disables ISIG, so an in-terminal
   Ctrl+C arrives as byte 0x03 and only an external signal lands here. */
static void on_exit_signal(int sig)
{
    (void)sig;
    restore_termios();
    _exit(0);
}

static void on_sigwinch(int sig)
{
    (void)sig;
    g_resize_requested = 1;
}

static void setup_signal_handlers(void)
{
    struct sigaction sa_term, sa_winch;
    sa_term.sa_handler = on_exit_signal;
    sigemptyset(&sa_term.sa_mask);
    sa_term.sa_flags = 0;
    sigaction(SIGTERM, &sa_term, NULL);
    sigaction(SIGINT, &sa_term, NULL);
    sa_winch.sa_handler = on_sigwinch;
    sigemptyset(&sa_winch.sa_mask);
    sa_winch.sa_flags = SA_RESTART;
    sigaction(SIGWINCH, &sa_winch, NULL);
    /* NB: SIGCHLD is deliberately NOT set to SIG_IGN here. The original
       fire-and-forget design had it auto-reap fetch_bg children, but SIG_IGN
       breaks system()/wait() for every later child: exec'd commands finish
       and are reaped by the kernel, leaving system() with ECHILD (-1/255).
       fetch_bg double-forks instead (the grandchild is reparented to init),
       so shell tools keep their exit codes. */
}

static int init_termios(void)
{
    struct termios raw;
    if (tcgetattr(STDIN_FILENO, &orig_termios) == -1)
        return -1;
    raw = orig_termios;
    raw.c_iflag &= ~(BRKINT | ICRNL | INPCK | ISTRIP | IXON);
    /* OPOST kept enabled: \n -> \r\n translation for proper line rendering */
    raw.c_cflag |= CS8;
    raw.c_lflag &= ~(ECHO | ICANON | ISIG | IEXTEN);
    raw.c_cc[VMIN] = 1;
    raw.c_cc[VTIME] = 0;
    if (tcsetattr(STDIN_FILENO, TCSANOW, &raw) == -1)
        return -1;
    termios_active = 1;
    return 0;
}

/* --- tether.* API exposed to Lua --- */

static int l_read_char(lua_State *L)
{
    /* bytes the watch picked up during a blocked turn come first */
    unsigned char queued;
    if (pending_take(&queued)) {
        lua_pushinteger(L, queued);
        return 1;
    }
    char c;
    ssize_t n = read(STDIN_FILENO, &c, 1);
    if (n != 1)
        lua_pushnil(L);
    else
        lua_pushinteger(L, (unsigned char)c);
    return 1;
}

/* Pure non-blocking drain: returns a byte only when one is already
 * available, nil otherwise — never waits. Readiness waiting belongs to the
 * reactor's poll (tether.poll), so no transfer or timer callback can stall
 * on input. Incomplete escape sequences are the decoder's job: it stashes
 * the prefix and retries whole on the next tick. */
static int l_read_char_nb(lua_State *L)
{
    unsigned char queued;
    if (pending_take(&queued)) {
        lua_pushinteger(L, queued);
        return 1;
    }
    fd_set fds;
    struct timeval tv;
    FD_ZERO(&fds);
    FD_SET(STDIN_FILENO, &fds);
    tv.tv_sec = 0;
    tv.tv_usec = 0;
    int ready = select(STDIN_FILENO + 1, &fds, NULL, NULL, &tv);
    if (ready <= 0) { lua_pushnil(L); return 1; }
    char c;
    ssize_t n = read(STDIN_FILENO, &c, 1);
    if (n != 1)
        lua_pushnil(L);
    else
        lua_pushinteger(L, (unsigned char)c);
    return 1;
}

static int l_write(lua_State *L)
{
    size_t len;
    const char *s = luaL_checklstring(L, 1, &len);
    ssize_t w = write(STDOUT_FILENO, s, len);
    if (w == -1)
        luaL_error(L, "write: %s", strerror(errno));
    if (w != (ssize_t)len) {
        /* partial write: retry remaining bytes */
        const char *ptr = s + w;
        size_t remaining = len - w;
        while (remaining > 0) {
            w = write(STDOUT_FILENO, ptr, remaining);
            if (w == -1) break;
            ptr += w;
            remaining -= w;
        }
    }
    fflush(stdout);
    return 0;
}

static int l_exec(lua_State *L)
{
    const char *cmd = luaL_checkstring(L, 1);
    /* fork/exec instead of system(): system() blocks Lua (and the spinner)
       for the whole command — the agent `run` tool allows up to 120 s. The
       parent waits in spinner quanta and ticks, so the indicator animates
       while the tool works. Contract unchanged: no kill on Ctrl+C (the
       interrupt surfaces at the next checkpoint), same (ok, exit_code). */
    pid_t pid = fork();
    if (pid < 0) {
        lua_pushboolean(L, 0);
        lua_pushinteger(L, 127);
        return 2;
    }
    if (pid == 0) {
        execl("/bin/sh", "sh", "-c", cmd, (char *)NULL);
        _exit(127);
    }
    int st = 0;
    for (;;) {
        pid_t w = waitpid(pid, &st, WNOHANG);
        if (w == pid)
            break;
        if (w < 0 && errno != EINTR)
            break; /* lost child: report through the status below */
        {
            struct timespec ts;
            ts.tv_sec = 0;
            ts.tv_nsec = (long)SPINNER_QUANTUM_MS * 1000L * 1000L;
            nanosleep(&ts, NULL);
        }
        spinner_tick_call(L);
    }
    int exit_code = WIFEXITED(st) ? WEXITSTATUS(st) : 127;
    lua_pushboolean(L, exit_code == 0);
    lua_pushinteger(L, exit_code);
    return 2;
}

static int l_realpath(lua_State *L)
{
    const char *path = luaL_checkstring(L, 1);
    char resolved[PATH_MAX];
    char *rp = realpath(path, resolved);
    if (rp == NULL) {
        lua_pushboolean(L, 0);
        return 1;
    }
    lua_pushstring(L, rp);
    return 1;
}

static int l_getcwd(lua_State *L)
{
    char buf[4096];
    if (getcwd(buf, sizeof(buf)) == NULL)
        luaL_error(L, "getcwd: %s", strerror(errno));
    lua_pushstring(L, buf);
    return 1;
}

static int l_get_terminal_size(lua_State *L)
{
    struct winsize ws;
    if (ioctl(STDIN_FILENO, TIOCGWINSZ, &ws) == 0) {
        lua_newtable(L);
        lua_pushinteger(L, ws.ws_col);
        lua_setfield(L, -2, "width");
        lua_pushinteger(L, ws.ws_row);
        lua_setfield(L, -2, "height");
    } else {
        lua_pushnil(L);
    }
    return 1;
}

static int l_tty(lua_State *L)
{
    lua_pushboolean(L, isatty(STDIN_FILENO) == 1);
    return 1;
}

/* --- fs API (mkdirp/fchmod/readdir/stat) --- */

/* qsort comparator for the directory-entry names collected by l_readdir */
static int fs_name_cmp(const void *a, const void *b)
{
    return strcmp(*(const char *const *)a, *(const char *const *)b);
}

/* tether.mkdirp(path) -> true | nil, err  (recursive; EEXIST ignored) */
static int l_mkdirp(lua_State *L)
{
    const char *path = luaL_checkstring(L, 1);
    size_t len = strlen(path);
    if (len == 0) {
        lua_pushnil(L);
        lua_pushstring(L, "empty path");
        return 2;
    }
    char *buf = malloc(len + 1);
    if (buf == NULL)
        return luaL_error(L, "mkdirp: out of memory");
    memcpy(buf, path, len + 1);

    /* create every prefix at each '/'; mkdir(2) reports EEXIST for the
       parts that already exist, which is the normal case when called twice */
    for (size_t i = 1; i <= len; i++) {
        if (buf[i] != '/' && buf[i] != '\0') continue;
        char saved = buf[i];
        buf[i] = '\0';
        int rc = mkdir(buf, 0777);
        int e = errno;
        buf[i] = saved;
        if (rc != 0 && e != EEXIST) {
            free(buf);
            lua_pushnil(L);
            lua_pushstring(L, strerror(e));
            return 2;
        }
    }

    /* the final component must resolve to a directory, not a file */
    struct stat st;
    if (stat(buf, &st) != 0 || !S_ISDIR(st.st_mode)) {
        int e = errno;
        free(buf);
        lua_pushnil(L);
        lua_pushstring(L, e != 0 ? strerror(e) : "not a directory");
        return 2;
    }
    free(buf);
    lua_pushboolean(L, 1);
    return 1;
}

/* tether.fchmod(path, mode) -> true | nil, err */
static int l_fchmod(lua_State *L)
{
    const char *path = luaL_checkstring(L, 1);
    int mode = (int)luaL_checkinteger(L, 2);
    int fd = open(path, O_WRONLY);
    if (fd < 0) {
        lua_pushnil(L);
        lua_pushstring(L, strerror(errno));
        return 2;
    }
    int rc = fchmod(fd, (mode_t)mode);
    int e = errno;
    close(fd);
    if (rc != 0) {
        lua_pushnil(L);
        lua_pushstring(L, strerror(e));
        return 2;
    }
    lua_pushboolean(L, 1);
    return 1;
}

/* tether.readdir(path) -> { names sorted, no . / .. } | nil, err */
static int l_readdir(lua_State *L)
{
    const char *path = luaL_checkstring(L, 1);
    DIR *dir = opendir(path);
    if (dir == NULL) {
        lua_pushnil(L);
        lua_pushstring(L, strerror(errno));
        return 2;
    }
    size_t cap = 32, len = 0;
    char **names = malloc(cap * sizeof(*names));
    if (names == NULL) {
        closedir(dir);
        return luaL_error(L, "readdir: out of memory");
    }
    struct dirent *ent;
    while ((ent = readdir(dir)) != NULL) {
        if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
            continue;
        if (len == cap) {
            cap *= 2;
            char **grown = realloc(names, cap * sizeof(*names));
            if (grown == NULL) {
                for (size_t i = 0; i < len; i++) free(names[i]);
                free(names);
                closedir(dir);
                return luaL_error(L, "readdir: out of memory");
            }
            names = grown;
        }
        names[len] = strdup(ent->d_name);
        if (names[len] == NULL) {
            for (size_t i = 0; i < len; i++) free(names[i]);
            free(names);
            closedir(dir);
            return luaL_error(L, "readdir: out of memory");
        }
        len++;
    }
    closedir(dir);
    qsort(names, len, sizeof(*names), fs_name_cmp);
    lua_createtable(L, (int)len, 0);
    for (size_t i = 0; i < len; i++) {
        lua_pushstring(L, names[i]);
        lua_rawseti(L, -2, (lua_Integer)i + 1);
        free(names[i]);
    }
    free(names);
    return 1;
}

/* tether.stat(path) -> { mtime, size, is_dir } | nil, err */
static int l_stat(lua_State *L)
{
    const char *path = luaL_checkstring(L, 1);
    struct stat st;
    if (lstat(path, &st) != 0) {
        lua_pushnil(L);
        lua_pushstring(L, strerror(errno));
        return 2;
    }
    lua_createtable(L, 0, 3);
    lua_pushinteger(L, (lua_Integer)st.st_mtime);
    lua_setfield(L, -2, "mtime");
    lua_pushinteger(L, (lua_Integer)st.st_size);
    lua_setfield(L, -2, "size");
    lua_pushboolean(L, S_ISDIR(st.st_mode) != 0);
    lua_setfield(L, -2, "is_dir");
    return 1;
}

/* --- krep recursive search --- */

/* Split one captured krep record ("path:lineno:text") in place.
   Returns 1 on success. The first ':' followed by a digit run and another ':'
   wins, which is the same rule the previous rg/grep parser used. */
static int krep_parse_line(char *line, char **path, long *lineno, char **text)
{
    for (char *c = line; (c = strchr(c, ':')) != NULL; c++) {
        char *digits = c + 1;
        if (!isdigit((unsigned char)*digits)) continue;
        char *end = digits;
        while (isdigit((unsigned char)*end)) end++;
        if (*end != ':') continue;
        *c = '\0';
        *end = '\0';
        *path = line;
        *lineno = strtol(digits, NULL, 10);
        *text = end + 1;
        return 1;
    }
    return 0;
}

/* tether.krep_search(base_dir, pattern, glob_filter, ignore_case,
 *                    use_gitignore, max_results)
 *   -> { {path, line, column, text}, ... } | nil, err
 *
 * krep's recursive search prints "path:lineno:line" records to stdout instead
 * of handing them back, so its output is captured through a temporary stream
 * and parsed. The printed form carries no column, so every record reports
 * column 1 (the tools spec allows that: "column is 1 when the engine omits
 * it"). With stdout not being a TTY, krep emits no ANSI color. */
static int l_krep_search(lua_State *L)
{
    const char *base_dir = luaL_checkstring(L, 1);
    const char *pattern = luaL_checkstring(L, 2);
    const char *glob_filter = luaL_optstring(L, 3, NULL);
    int ignore_case = lua_toboolean(L, 4);
    int use_gitignore = lua_toboolean(L, 5);
    lua_Integer max_results = luaL_optinteger(L, 6, 100);
    if (max_results < 0) max_results = 0;

    size_t pattern_len = strlen(pattern);
    search_params_t params;
    memset(&params, 0, sizeof(params));
    params.pattern = pattern;
    params.pattern_len = pattern_len;
    params.patterns = &pattern;
    params.pattern_lens = &pattern_len;
    params.num_patterns = 1;
    params.case_sensitive = ignore_case ? false : true;
    params.use_regex = true; /* POSIX ERE, matching the old tool default */
    params.track_positions = true;
    params.max_count = (max_results > 0) ? (size_t)max_results : SIZE_MAX;

    /* line numbers on so records carry a line; glob_filter is krep's --glob */
    krep_set_options(use_gitignore ? true : false, true, glob_filter);

    FILE *cap = tmpfile();
    if (cap == NULL) {
        lua_pushnil(L);
        lua_pushstring(L, "cannot create capture stream");
        return 2;
    }

    fflush(stdout);
    int saved_fd = dup(STDOUT_FILENO);
    if (saved_fd < 0 || dup2(fileno(cap), STDOUT_FILENO) < 0) {
        if (saved_fd >= 0) close(saved_fd);
        fclose(cap);
        lua_pushnil(L);
        lua_pushstring(L, "cannot capture krep output");
        return 2;
    }
    /* krep reports everything from permission problems to regex failures on
       stderr, straight over the alt-screen TUI. Silence it for the call. */
    fflush(stderr);
    int saved_err = dup(STDERR_FILENO);
    int devnull = -1;
    if (saved_err >= 0) {
        devnull = open("/dev/null", O_WRONLY);
        if (devnull >= 0)
            dup2(devnull, STDERR_FILENO);
    }

    /* tools.grep passes the model's path through untouched, so it is
       routinely a FILE (grep this one file), not a directory. opendir on
       it failed ENOTDIR with the complaint above and zero records. */
    struct stat base_st;
    if (stat(base_dir, &base_st) == 0 && S_ISREG(base_st.st_mode))
        search_file(&params, base_dir, 0);
    else
        search_directory_recursive(base_dir, &params, 0);

    fflush(stdout);
    dup2(saved_fd, STDOUT_FILENO);
    close(saved_fd);
    if (saved_err >= 0) {
        fflush(stderr);
        dup2(saved_err, STDERR_FILENO);
        close(saved_err);
    }
    if (devnull >= 0)
        close(devnull);

    /* slurp the capture */
    char *buf = NULL;
    if (fseek(cap, 0, SEEK_END) == 0) {
        long size = ftell(cap);
        if (size >= 0) {
            rewind(cap);
            buf = malloc((size_t)size + 1);
            if (buf != NULL) {
                size_t got = fread(buf, 1, (size_t)size, cap);
                buf[got] = '\0';
            }
        }
    }
    fclose(cap);
    if (buf == NULL)
        return luaL_error(L, "krep_search: cannot read captured output");

    lua_newtable(L);
    int count = 0;
    char *line = buf;
    while (line != NULL && *line != '\0') {
        if (max_results > 0 && count >= (int)max_results) break;
        char *nl = strchr(line, '\n');
        if (nl != NULL) *nl = '\0';
        char *path = NULL, *text = NULL;
        long lineno = 0;
        if (krep_parse_line(line, &path, &lineno, &text)) {
            lua_createtable(L, 0, 4);
            lua_pushstring(L, path);
            lua_setfield(L, -2, "path");
            lua_pushinteger(L, (lua_Integer)lineno);
            lua_setfield(L, -2, "line");
            lua_pushinteger(L, 1); /* krep's printed form omits the column */
            lua_setfield(L, -2, "column");
            lua_pushstring(L, text);
            lua_setfield(L, -2, "text");
            lua_rawseti(L, -2, ++count);
        }
        line = (nl != NULL) ? nl + 1 : NULL;
    }
    free(buf);
    return 1;
}

/* --- in-process HTTP(S) via vendor'd libcurl + mbedTLS + zlib --- */

/* RS256 (PKCS#1 v1.5 over SHA-256) with a PEM RSA private key, via the
   vendor'd mbedTLS. Exposed to Lua as tether.rs256_sign for the Google
   service-account ADC JWT (auth.resolve_adc_token). Returns a base64url
   (unpadded) signature or nil. */
/* RNG callback for pk_sign (padding needs a few random bytes). Reading
   /dev/urandom directly keeps the entropy/DRBG machinery out of the binary. */
static int urandom_rng(void *p_rng, unsigned char *out, size_t len)
{
    (void)p_rng;
    FILE *f = fopen("/dev/urandom", "rb");
    if (f == NULL) return 0x006C; /* MBEDTLS_ERR_ENTROPY_SOURCE_FAILED */
    size_t got = fread(out, 1, len, f);
    fclose(f);
    return got == len ? 0 : 0x006C;
}

static int l_rs256_sign(lua_State *L)
{
    const char *pem = luaL_checkstring(L, 1);
    size_t msglen;
    const char *msg = luaL_checklstring(L, 2, &msglen);

    mbedtls_pk_context pk;
    mbedtls_pk_init(&pk);
    /* unencrypted PEM keys never invoke the RNG during parse, but the API
       still wants a callback; any failure here means an unusable key. */
    if (mbedtls_pk_parse_key(&pk, (const unsigned char *)pem,
                             strlen(pem) + 1, NULL, 0,
                             urandom_rng, NULL) != 0) {
        mbedtls_pk_free(&pk);
        lua_pushnil(L);
        return 1;
    }
    unsigned char hash[32];
    if (mbedtls_sha256((const unsigned char *)msg, msglen, hash, 0) != 0) {
        mbedtls_pk_free(&pk);
        lua_pushnil(L);
        return 1;
    }
    unsigned char sig[MBEDTLS_PK_SIGNATURE_MAX_SIZE];
    size_t siglen = 0;
    int rc = mbedtls_pk_sign(&pk, MBEDTLS_MD_SHA256, hash, sizeof(hash),
                             sig, sizeof(sig), &siglen,
                             urandom_rng, NULL);
    mbedtls_pk_free(&pk);
    if (rc != 0) {
        lua_pushnil(L);
        return 1;
    }
    /* base64url, no padding */
    static const char alpha[] =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    size_t cap = ((siglen + 2) / 3) * 4 + 1;
    char *out = malloc(cap);
    if (out == NULL) {
        lua_pushnil(L);
        return 1;
    }
    size_t o = 0;
    for (size_t i = 0; i < siglen; i += 3) {
        unsigned n = ((unsigned)sig[i] << 16)
            | (i + 1 < siglen ? (unsigned)sig[i + 1] << 8 : 0)
            | (i + 2 < siglen ? (unsigned)sig[i + 2] : 0);
        out[o++] = alpha[(n >> 18) & 63];
        out[o++] = alpha[(n >> 12) & 63];
        if (i + 1 < siglen) out[o++] = alpha[(n >> 6) & 63];
        if (i + 2 < siglen) out[o++] = alpha[n & 63];
    }
    lua_pushlstring(L, out, o);
    free(out);
    return 1;
}

/* The OS-distributed trust anchor; there is no per-call override and curl's
   own CURL_CA_BUNDLE handling is overridden by setting CAINFO explicitly. */
static const char *tether_ca_bundle(void)
{
    static const char *candidates[] = {
        "/etc/ssl/certs/ca-certificates.crt",
        "/etc/pki/tls/certs/ca-bundle.crt",
        "/etc/ssl/ca-bundle.pem",
    };
    for (size_t i = 0; i < sizeof(candidates) / sizeof(candidates[0]); i++) {
        if (access(candidates[i], R_OK) == 0)
            return candidates[i];
    }
    return NULL;
}

/* Read a whole file into a NUL-terminated buffer (caller frees). */
static int read_file_all(const char *path, char **out, size_t *outlen,
                         char *err, size_t errlen)
{
    FILE *f = fopen(path, "rb");
    if (f == NULL) {
        snprintf(err, errlen, "cannot open %s", path);
        return 0;
    }
    if (fseek(f, 0, SEEK_END) != 0) {
        fclose(f);
        snprintf(err, errlen, "cannot read %s", path);
        return 0;
    }
    long size = ftell(f);
    if (size < 0) {
        fclose(f);
        snprintf(err, errlen, "cannot read %s", path);
        return 0;
    }
    rewind(f);
    char *buf = malloc((size_t)size + 1);
    if (buf == NULL) {
        fclose(f);
        snprintf(err, errlen, "out of memory");
        return 0;
    }
    size_t got = fread(buf, 1, (size_t)size, f);
    fclose(f);
    buf[got] = '\0';
    *out = buf;
    *outlen = got;
    return 1;
}

/* Build a curl_slist from a Lua header array. A "@path" entry names a file
   whose non-empty lines are added as header lines (curl's -H @file), which is
   how the auth header temp file travels without the key entering argv. */
static struct curl_slist *http_build_headers(lua_State *L, int idx,
                                             char *err, size_t errlen)
{
    struct curl_slist *list = NULL;
    if (!lua_istable(L, idx))
        return NULL;
    int n = (int)lua_rawlen(L, idx);
    for (int i = 1; i <= n; i++) {
        lua_geti(L, idx, i);
        const char *entry = lua_tostring(L, -1);
        if (entry == NULL) {
            lua_pop(L, 1);
            continue;
        }
        if (entry[0] == '@') {
            FILE *f = fopen(entry + 1, "r");
            if (f == NULL) {
                snprintf(err, errlen, "cannot read header file");
                lua_pop(L, 1);
                curl_slist_free_all(list);
                return NULL;
            }
            char line[4096];
            while (fgets(line, sizeof(line), f) != NULL) {
                size_t len = strlen(line);
                while (len > 0 && (line[len - 1] == '\n' || line[len - 1] == '\r'))
                    line[--len] = '\0';
                if (len > 0)
                    list = curl_slist_append(list, line);
            }
            fclose(f);
        } else {
            list = curl_slist_append(list, entry);
        }
        lua_pop(L, 1);
    }
    return list;
}

/* Apply the options every request shares. Returns 1 on success. */
static int http_apply_common(CURL *h, const char *url, const char *ca,
                             struct curl_slist *headers)
{
    curl_easy_setopt(h, CURLOPT_URL, url);
    curl_easy_setopt(h, CURLOPT_CAINFO, ca);
    curl_easy_setopt(h, CURLOPT_SSL_VERIFYPEER, 1L);
    curl_easy_setopt(h, CURLOPT_SSL_VERIFYHOST, 2L);
    curl_easy_setopt(h, CURLOPT_FOLLOWLOCATION, 1L);
    curl_easy_setopt(h, CURLOPT_NOSIGNAL, 1L);
    curl_easy_setopt(h, CURLOPT_HTTPHEADER, headers);
    curl_easy_setopt(h, CURLOPT_USERAGENT, "tether");
    curl_easy_setopt(h, CURLOPT_ACCEPT_ENCODING, ""); /* gzip/deflate via zlib */
    return 1;
}

/* Growable buffer for http_get. */
struct body_buf {
    char *data;
    size_t len;
    size_t cap;
};

static size_t http_body_cb(char *ptr, size_t size, size_t nmemb, void *userdata)
{
    struct body_buf *b = userdata;
    size_t total = size * nmemb;
    if (b->len + total + 1 > b->cap) {
        size_t cap = b->cap ? b->cap : 8192;
        while (cap < b->len + total + 1)
            cap *= 2;
        char *grown = realloc(b->data, cap);
        if (grown == NULL)
            return 0;
        b->data = grown;
        b->cap = cap;
    }
    memcpy(b->data + b->len, ptr, total);
    b->len += total;
    b->data[b->len] = '\0';
    return total;
}

/* Read the request body: a Lua string is used as-is, "@path" is read from a
   file (curl's --data-binary @file). */
static int http_read_body(const char *body, char **out, size_t *outlen,
                          char *err, size_t errlen)
{
    *out = NULL;
    *outlen = 0;
    if (body == NULL)
        return 1;
    if (body[0] == '@')
        return read_file_all(body + 1, out, outlen, err, errlen);
    *outlen = strlen(body);
    *out = malloc(*outlen + 1);
    if (*out == NULL) {
        snprintf(err, errlen, "out of memory");
        return 0;
    }
    memcpy(*out, body, *outlen + 1);
    return 1;
}

/* --- Incremental HTTP transfers for the reactor ---------------------------
 * Same wire behavior as http_stream, but the loop belongs to Lua: start the
 * request, poll the sockets together with stdin, step with a bounded
 * timeout, drain complete lines, abort, free. The write callback queues
 * lines in C and never calls Lua, so no transfer callback can block on
 * input or reenter the interpreter. */
struct xfer_line_q {
    char **v;
    size_t n, cap;
};

struct http_xfer {
    CURLM *m;
    CURL *h;
    struct curl_slist *headers;
    char *body_buf;
    struct xfer_line_q lines;
    char *part;
    size_t part_len, part_cap;
    int running;
    int done;
    int aborted;
    int failed;
    char err[256];
};

static int xfer_queue_line(struct http_xfer *x, const char *s, size_t len)
{
    if (x->lines.n == x->lines.cap) {
        size_t cap = x->lines.cap ? x->lines.cap * 2 : 32;
        char **grown = realloc(x->lines.v, cap * sizeof(*grown));
        if (grown == NULL)
            return 0;
        x->lines.v = grown;
        x->lines.cap = cap;
    }
    char *copy = malloc(len + 1);
    if (copy == NULL)
        return 0;
    memcpy(copy, s, len);
    copy[len] = '\0';
    x->lines.v[x->lines.n++] = copy;
    return 1;
}

/* Queue complete lines; the trailing partial line stays buffered until the
 * transfer finishes (same framing as http_stream: split on '\n' only). */
static size_t xfer_write_cb(char *ptr, size_t size, size_t nmemb, void *userdata)
{
    struct http_xfer *x = userdata;
    size_t total = size * nmemb;
    size_t start = 0;
    for (size_t i = 0; i < total; i++) {
        if (ptr[i] != '\n')
            continue;
        size_t seg = i - start;
        size_t len = x->part_len + seg;
        char *line = malloc(len + 1);
        if (line == NULL)
            return 0;
        if (x->part_len > 0)
            memcpy(line, x->part, x->part_len);
        memcpy(line + x->part_len, ptr + start, seg);
        line[len] = '\0';
        x->part_len = 0;
        if (!xfer_queue_line(x, line, len)) {
            free(line);
            return 0;
        }
        free(line);
        start = i + 1;
    }
    size_t tail = total - start;
    if (tail > 0) {
        if (x->part_len + tail + 1 > x->part_cap) {
            size_t cap = x->part_cap ? x->part_cap : 4096;
            while (cap < x->part_len + tail + 1)
                cap *= 2;
            char *grown = realloc(x->part, cap);
            if (grown == NULL)
                return 0;
            x->part = grown;
            x->part_cap = cap;
        }
        memcpy(x->part + x->part_len, ptr + start, tail);
        x->part_len += tail;
    }
    return total;
}

/* A final line without a trailing newline still counts (http_stream parity). */
static void xfer_flush_part(struct http_xfer *x)
{
    if (x->part_len == 0)
        return;
    if (xfer_queue_line(x, x->part, x->part_len))
        x->part_len = 0;
}

static void xfer_destroy(struct http_xfer *x)
{
    if (x == NULL)
        return;
    if (x->h != NULL && x->m != NULL)
        curl_multi_remove_handle(x->m, x->h);
    if (x->h != NULL)
        curl_easy_cleanup(x->h);
    if (x->m != NULL)
        curl_multi_cleanup(x->m);
    curl_slist_free_all(x->headers);
    free(x->body_buf);
    for (size_t i = 0; i < x->lines.n; i++)
        free(x->lines.v[i]);
    free(x->lines.v);
    free(x->part);
    free(x);
}

/* Shared easy-handle setup; takes ownership of headers/body_buf on success. */
static struct http_xfer *xfer_create(const char *method, const char *url,
                                     struct curl_slist *headers, char *body_buf,
                                     size_t body_len, double connect_s,
                                     double idle_s, char *err, size_t errlen)
{
    struct http_xfer *x = calloc(1, sizeof(*x));
    if (x == NULL) {
        snprintf(err, errlen, "out of memory");
        return NULL;
    }
    x->headers = headers;
    x->body_buf = body_buf;
    x->h = curl_easy_init();
    if (x->h == NULL) {
        snprintf(err, errlen, "cannot create HTTP handle");
        curl_slist_free_all(headers);
        free(body_buf);
        free(x);
        return NULL;
    }
    const char *ca = tether_ca_bundle();
    if (ca == NULL) {
        snprintf(err, errlen, "no system CA bundle found");
        curl_easy_cleanup(x->h);
        curl_slist_free_all(headers);
        free(body_buf);
        free(x);
        return NULL;
    }
    http_apply_common(x->h, url, ca, headers);
    curl_easy_setopt(x->h, CURLOPT_CONNECTTIMEOUT_MS, (long)(connect_s * 1000.0));
    curl_easy_setopt(x->h, CURLOPT_LOW_SPEED_LIMIT, 1L);
    curl_easy_setopt(x->h, CURLOPT_LOW_SPEED_TIME, (long)idle_s);
    curl_easy_setopt(x->h, CURLOPT_WRITEFUNCTION, xfer_write_cb);
    curl_easy_setopt(x->h, CURLOPT_WRITEDATA, x);
    /* No progress callback: the reactor owns stdin and abort. Aborts arrive
       via http_abort between steps, never from inside the transfer. */
    if (body_buf != NULL) {
        curl_easy_setopt(x->h, CURLOPT_POSTFIELDS, body_buf);
        curl_easy_setopt(x->h, CURLOPT_POSTFIELDSIZE, (long)body_len);
    }
    if (method[0] != '\0' && strcasecmp(method, "POST") != 0)
        curl_easy_setopt(x->h, CURLOPT_CUSTOMREQUEST, method);
    x->m = curl_multi_init();
    if (x->m == NULL) {
        snprintf(err, errlen, "cannot create HTTP multi handle");
        xfer_destroy(x);
        return NULL;
    }
    if (curl_multi_add_handle(x->m, x->h) != CURLM_OK) {
        snprintf(err, errlen, "cannot start HTTP transfer");
        xfer_destroy(x);
        return NULL;
    }
    x->running = 1;
    int still_running = 0;
    if (curl_multi_perform(x->m, &still_running) != CURLM_OK)
        still_running = 0;
    if (!still_running) {
        /* finished synchronously (fast failure, e.g. refused): collect it */
        CURLMsg *msg;
        int left = 0;
        while ((msg = curl_multi_info_read(x->m, &left)) != NULL) {
            if (msg->msg == CURLMSG_DONE && msg->easy_handle == x->h) {
                x->running = 0;
                x->done = 1;
                if (msg->data.result == CURLE_OK) {
                    xfer_flush_part(x);
                } else {
                    x->failed = 1;
                    snprintf(x->err, sizeof(x->err), "%s",
                             curl_easy_strerror(msg->data.result));
                }
            }
        }
        if (!x->done) {
            /* no message but nothing running: treat as done */
            x->running = 0;
            x->done = 1;
            xfer_flush_part(x);
        }
    }
    return x;
}

static struct http_xfer *check_xfer(lua_State *L, int idx)
{
    struct http_xfer **pp = luaL_checkudata(L, idx, "tether.http_xfer");
    if (pp == NULL || *pp == NULL)
        luaL_error(L, "http handle is closed");
    return *pp;
}

/* tether.http_start(method, url, headers, body, opts) -> handle | nil, err */
static int l_http_start(lua_State *L)
{
    const char *method = luaL_checkstring(L, 1);
    const char *url = luaL_checkstring(L, 2);
    const char *body = luaL_optstring(L, 4, NULL);
    double connect_s = 10.0, idle_s = 60.0;
    if (lua_istable(L, 5)) {
        lua_getfield(L, 5, "timeout_s");
        if (lua_isnumber(L, -1)) connect_s = lua_tonumber(L, -1);
        lua_pop(L, 1);
        lua_getfield(L, 5, "connect_timeout_s");
        if (lua_isnumber(L, -1)) connect_s = lua_tonumber(L, -1);
        lua_pop(L, 1);
        lua_getfield(L, 5, "idle_timeout_s");
        if (lua_isnumber(L, -1)) idle_s = lua_tonumber(L, -1);
        lua_pop(L, 1);
    }
    char err[256] = {0};
    struct curl_slist *headers = http_build_headers(L, 3, err, sizeof(err));
    if (err[0] != '\0') {
        lua_pushnil(L);
        lua_pushstring(L, err);
        return 2;
    }
    char *body_buf = NULL;
    size_t body_len = 0;
    if (!http_read_body(body, &body_buf, &body_len, err, sizeof(err))) {
        curl_slist_free_all(headers);
        lua_pushnil(L);
        lua_pushstring(L, err);
        return 2;
    }
    struct http_xfer *x = xfer_create(method, url, headers, body_buf,
                                      body_len, connect_s, idle_s,
                                      err, sizeof(err));
    if (x == NULL) {
        lua_pushnil(L);
        lua_pushstring(L, err);
        return 2;
    }
    struct http_xfer **pp = lua_newuserdatauv(L, sizeof(*pp), 0);
    *pp = x;
    luaL_getmetatable(L, "tether.http_xfer");
    lua_setmetatable(L, -2);
    return 1;
}

/* tether.http_step(handle, timeout_ms) -> "running" | "done" | "failed" [, err]
 * Advances the transfer by at most timeout_ms. Never touches stdin. */
static int l_http_step(lua_State *L)
{
    struct http_xfer *x = check_xfer(L, 1);
    long timeout_ms = luaL_optinteger(L, 2, 80);
    if (timeout_ms < 0)
        timeout_ms = 0;
    if (x->done) {
        if (x->failed) {
            lua_pushstring(L, "failed");
            lua_pushstring(L, x->err);
            return 2;
        }
        lua_pushstring(L, "done");
        return 1;
    }
    if (x->aborted) {
        curl_multi_remove_handle(x->m, x->h);
        x->running = 0;
        x->done = 1;
        x->failed = 1;
        snprintf(x->err, sizeof(x->err), "aborted");
        lua_pushstring(L, "failed");
        lua_pushstring(L, x->err);
        return 2;
    }
    int numfds = 0;
    if (curl_multi_poll(x->m, NULL, 0, (int)timeout_ms, &numfds) != CURLM_OK) {
        x->running = 0;
        x->done = 1;
        x->failed = 1;
        snprintf(x->err, sizeof(x->err), "poll failed");
        lua_pushstring(L, "failed");
        lua_pushstring(L, x->err);
        return 2;
    }
    int still_running = 0;
    if (curl_multi_perform(x->m, &still_running) != CURLM_OK)
        still_running = 0;
    CURLMsg *msg;
    int left = 0;
    while ((msg = curl_multi_info_read(x->m, &left)) != NULL) {
        if (msg->msg == CURLMSG_DONE && msg->easy_handle == x->h) {
            x->running = 0;
            x->done = 1;
            if (msg->data.result == CURLE_OK) {
                xfer_flush_part(x);
            } else {
                x->failed = 1;
                snprintf(x->err, sizeof(x->err), "%s",
                         curl_easy_strerror(msg->data.result));
            }
        }
    }
    if (!still_running && !x->done) {
        x->running = 0;
        x->done = 1;
        xfer_flush_part(x);
    } else {
        x->running = still_running;
    }
    if (x->done) {
        if (x->failed) {
            lua_pushstring(L, "failed");
            lua_pushstring(L, x->err);
            return 2;
        }
        lua_pushstring(L, "done");
        return 1;
    }
    lua_pushstring(L, "running");
    return 1;
}

/* tether.http_lines(handle) -> {lines}: drain queued complete lines. */
static int l_http_lines(lua_State *L)
{
    struct http_xfer *x = check_xfer(L, 1);
    lua_newtable(L);
    for (size_t i = 0; i < x->lines.n; i++) {
        lua_pushstring(L, x->lines.v[i]);
        lua_rawseti(L, -2, (lua_Integer)i + 1);
        free(x->lines.v[i]);
    }
    free(x->lines.v);
    x->lines.v = NULL;
    x->lines.n = 0;
    x->lines.cap = 0;
    return 1;
}

/* tether.http_abort(handle): end the transfer as a failure on the next step. */
static int l_http_abort(lua_State *L)
{
    struct http_xfer *x = check_xfer(L, 1);
    x->aborted = 1;
    lua_pushboolean(L, 1);
    return 1;
}

/* tether.http_free(handle): release the transfer immediately. */
static int l_http_free(lua_State *L)
{
    struct http_xfer **pp = luaL_checkudata(L, 1, "tether.http_xfer");
    if (pp != NULL && *pp != NULL) {
        xfer_destroy(*pp);
        *pp = NULL;
    }
    lua_pushboolean(L, 1);
    return 1;
}

/* tether.http_fds(handle) -> {read={fd}, write={fd}, exc={fd}, timeout=ms|-1}:
 * the sockets the reactor must poll alongside stdin. */
static int l_http_fds(lua_State *L)
{
    struct http_xfer *x = check_xfer(L, 1);
    fd_set rfds, wfds, efds;
    FD_ZERO(&rfds);
    FD_ZERO(&wfds);
    FD_ZERO(&efds);
    int maxfd = -1;
    curl_multi_fdset(x->m, &rfds, &wfds, &efds, &maxfd);
    long timeout = -1;
    curl_multi_timeout(x->m, &timeout);
    lua_newtable(L);
    lua_newtable(L);
    lua_newtable(L);
    lua_newtable(L);
    if (maxfd >= 0) {
        int ri = 1, wi = 1, ei = 1;
        for (int fd = 0; fd <= maxfd; fd++) {
            if (FD_ISSET(fd, &rfds)) {
                lua_pushinteger(L, fd);
                lua_rawseti(L, -4, ri++);
            }
            if (FD_ISSET(fd, &wfds)) {
                lua_pushinteger(L, fd);
                lua_rawseti(L, -3, wi++);
            }
            if (FD_ISSET(fd, &efds)) {
                lua_pushinteger(L, fd);
                lua_rawseti(L, -2, ei++);
            }
        }
    }
    lua_setfield(L, -4, "exc");
    lua_setfield(L, -3, "write");
    lua_setfield(L, -2, "read");
    lua_pushinteger(L, timeout);
    lua_setfield(L, -2, "timeout");
    return 1;
}

/* tether.poll(read_fds, write_fds, timeout_ms) -> {read={...}, write={...}}:
 * the reactor's single wait: poll the given descriptors with a bounded
 * timeout. Never touches Lua state beyond its arguments and result. */
static int l_poll(lua_State *L)
{
    struct pollfd pfds[256];
    char which[256];
    int n = 0;
    if (lua_istable(L, 1)) {
        size_t len = lua_rawlen(L, 1);
        for (size_t i = 1; i <= len && n < 256; i++) {
            lua_geti(L, 1, (lua_Integer)i);
            if (lua_isinteger(L, -1)) {
                pfds[n].fd = (int)lua_tointeger(L, -1);
                pfds[n].events = POLLIN;
                pfds[n].revents = 0;
                which[n] = 0;
                n++;
            }
            lua_pop(L, 1);
        }
    }
    if (lua_istable(L, 2)) {
        size_t len = lua_rawlen(L, 2);
        for (size_t i = 1; i <= len && n < 256; i++) {
            lua_geti(L, 2, (lua_Integer)i);
            if (lua_isinteger(L, -1)) {
                pfds[n].fd = (int)lua_tointeger(L, -1);
                pfds[n].events = POLLOUT;
                pfds[n].revents = 0;
                which[n] = 1;
                n++;
            }
            lua_pop(L, 1);
        }
    }
    long timeout_ms = luaL_optinteger(L, 3, 80);
    if (timeout_ms < 0)
        timeout_ms = 0;
    if (n > 0)
        poll(pfds, (nfds_t)n, (int)timeout_ms);
    else if (timeout_ms > 0) {
        struct timespec ts;
        ts.tv_sec = timeout_ms / 1000;
        ts.tv_nsec = (timeout_ms % 1000) * 1000L * 1000L;
        nanosleep(&ts, NULL);
    }
    lua_newtable(L);
    lua_newtable(L);
    lua_newtable(L);
    int ri = 1, wi = 1;
    for (int i = 0; i < n; i++) {
        if ((pfds[i].revents & (POLLIN | POLLHUP | POLLERR)) != 0 && which[i] == 0) {
            lua_pushinteger(L, pfds[i].fd);
            lua_rawseti(L, -3, ri++);
        }
        if ((pfds[i].revents & (POLLOUT | POLLERR)) != 0 && which[i] == 1) {
            lua_pushinteger(L, pfds[i].fd);
            lua_rawseti(L, -2, wi++);
        }
    }
    lua_setfield(L, -3, "write");
    lua_setfield(L, -2, "read");
    return 1;
}

/* tether.http_stream(method, url, headers, body, on_line, opts) -> true | nil, err
 *
 * on_line(line) is called for every body line (the newline is not included).
 * opts: {timeout_s} connect timeout, default 10 s; {idle_timeout_s} max gap
 * between body bytes, default 60 s. There is deliberately no total timeout so
 * long SSE streams stay open. An HTTP error status is NOT a transport failure:
 * the body is still streamed so the caller can inspect the error JSON.
 * Implemented over the incremental transfer API (same framing as stepped
 * drains); the blocking watch and spinner-tick behavior are unchanged. */
static int l_http_stream(lua_State *L)
{
    const char *method = luaL_checkstring(L, 1);
    const char *url = luaL_checkstring(L, 2);
    const char *body = luaL_optstring(L, 4, NULL);
    luaL_checktype(L, 5, LUA_TFUNCTION);

    double connect_s = 10.0, idle_s = 60.0;
    if (lua_istable(L, 6)) {
        lua_getfield(L, 6, "timeout_s");
        if (lua_isnumber(L, -1)) connect_s = lua_tonumber(L, -1);
        lua_pop(L, 1);
        lua_getfield(L, 6, "connect_timeout_s");
        if (lua_isnumber(L, -1)) connect_s = lua_tonumber(L, -1);
        lua_pop(L, 1);
        lua_getfield(L, 6, "idle_timeout_s");
        if (lua_isnumber(L, -1)) idle_s = lua_tonumber(L, -1);
        lua_pop(L, 1);
    }

    char err[256] = {0};
    struct curl_slist *headers = http_build_headers(L, 3, err, sizeof(err));
    if (err[0] != '\0') {
        lua_pushnil(L);
        lua_pushstring(L, err);
        return 2;
    }

    char *body_buf = NULL;
    size_t body_len = 0;
    if (!http_read_body(body, &body_buf, &body_len, err, sizeof(err))) {
        curl_slist_free_all(headers);
        lua_pushnil(L);
        lua_pushstring(L, err);
        return 2;
    }

    lua_pushvalue(L, 5);
    int fn_ref = luaL_ref(L, LUA_REGISTRYINDEX);

    struct http_xfer *x = xfer_create(method, url, headers, body_buf,
                                      body_len, connect_s, idle_s,
                                      err, sizeof(err));
    if (x == NULL) {
        luaL_unref(L, LUA_REGISTRYINDEX, fn_ref);
        lua_pushnil(L);
        lua_pushstring(L, err);
        return 2;
    }

    int lua_error = 0;
    char lua_err[256] = {0};
    while (!x->done) {
        if (poll_interrupt()) {
            x->aborted = 1;
        }
        /* one step per spinner quantum, like the old multi loop */
        int numfds = 0;
        if (!x->done && !x->aborted) {
            if (curl_multi_poll(x->m, NULL, 0,
                                SPINNER_QUANTUM_MS, &numfds) != CURLM_OK) {
                x->done = 1;
                x->failed = 1;
                snprintf(x->err, sizeof(x->err), "poll failed");
            } else {
                int still_running = 0;
                if (curl_multi_perform(x->m, &still_running) != CURLM_OK)
                    still_running = 0;
                CURLMsg *msg;
                int left = 0;
                while ((msg = curl_multi_info_read(x->m, &left)) != NULL) {
                    if (msg->msg == CURLMSG_DONE && msg->easy_handle == x->h) {
                        x->done = 1;
                        if (msg->data.result == CURLE_OK) {
                            xfer_flush_part(x);
                        } else {
                            x->failed = 1;
                            snprintf(x->err, sizeof(x->err), "%s",
                                     curl_easy_strerror(msg->data.result));
                        }
                    }
                }
                if (!still_running && !x->done) {
                    x->done = 1;
                    xfer_flush_part(x);
                }
            }
        }
        if (x->aborted && !x->done) {
            curl_multi_remove_handle(x->m, x->h);
            x->done = 1;
            x->failed = 1;
            snprintf(x->err, sizeof(x->err), "%s",
                     curl_easy_strerror(CURLE_ABORTED_BY_CALLBACK));
        }
        /* deliver every queued line in order, exactly like the old callback */
        for (size_t i = 0; i < x->lines.n && !lua_error; i++) {
            lua_rawgeti(L, LUA_REGISTRYINDEX, fn_ref);
            lua_pushstring(L, x->lines.v[i]);
            if (lua_pcall(L, 1, 0, 0) != LUA_OK) {
                lua_error = 1;
                const char *m = lua_tostring(L, -1);
                snprintf(lua_err, sizeof(lua_err), "%s", m ? m : "?");
                lua_pop(L, 1);
            }
            free(x->lines.v[i]);
        }
        free(x->lines.v);
        x->lines.v = NULL;
        x->lines.n = 0;
        x->lines.cap = 0;
        if (lua_error) {
            x->aborted = 1;
            if (!x->done) {
                curl_multi_remove_handle(x->m, x->h);
                x->done = 1;
                x->failed = 1;
            }
        }
        spinner_tick_call(L);
    }

    luaL_unref(L, LUA_REGISTRYINDEX, fn_ref);
    if (lua_error) {
        xfer_destroy(x);
        lua_pushnil(L);
        lua_pushstring(L, lua_err);
        return 2;
    }
    if (x->failed) {
        char ebuf[256];
        snprintf(ebuf, sizeof(ebuf), "%s", x->err[0] ? x->err : "transfer failed");
        xfer_destroy(x);
        lua_pushnil(L);
        lua_pushstring(L, ebuf);
        return 2;
    }
    xfer_destroy(x);
    lua_pushboolean(L, 1);
    return 1;
}

/* tether.fetch_bg(url, headers, outpath, timeout_s) -> true | nil, err
 *
 * Fire-and-forget GET for background model-list refresh: fork()s and returns
 * immediately; the child performs the transfer with the given total timeout
 * (default 20 s), writes the body to outpath (atomically via rename) on
 * HTTP < 400 or a "FETCH_FAILED <err>" marker otherwise, then _exit()s.
 * The Lua side picks the file up later (commands.poll_models_refresh).
 * @file header entries are read into memory before fork and unlinked right
 * away, so no temp-file race exists. The child never touches the terminal
 * (stdio goes to /dev/null) and the grandchild is reaped by init (double
 * fork — SIGCHLD stays at its default disposition so system()/wait keep
 * working). There is no Lua interaction in the child, so no state can leak
 * back except the outpath file. */
static int l_fetch_bg(lua_State *L)
{
    const char *url = luaL_checkstring(L, 1);
    const char *outpath = luaL_checkstring(L, 3);
    double timeout_s = 20.0;
    if (lua_isnumber(L, 4))
        timeout_s = lua_tonumber(L, 4);

    const char *ca = tether_ca_bundle();
    if (ca == NULL) {
        lua_pushnil(L);
        lua_pushstring(L, "no system CA bundle found");
        return 2;
    }

    char err[256] = {0};
    struct curl_slist *headers = http_build_headers(L, 2, err, sizeof(err));
    if (err[0] != '\0') {
        lua_pushnil(L);
        lua_pushstring(L, err);
        return 2;
    }

    /* @file entries live in the slist now: drop the temp files before fork. */
    if (lua_istable(L, 2)) {
        int n = (int)lua_rawlen(L, 2);
        for (int i = 1; i <= n; i++) {
            lua_geti(L, 2, i);
            const char *entry = lua_tostring(L, -1);
            if (entry != NULL && entry[0] == '@')
                unlink(entry + 1);
            lua_pop(L, 1);
        }
    }

    pid_t pid = fork();
    if (pid < 0) {
        curl_slist_free_all(headers);
        lua_pushnil(L);
        lua_pushstring(L, strerror(errno));
        return 2;
    }
    if (pid > 0) {
        curl_slist_free_all(headers);
        /* Reap the intermediate child so no zombie accumulates. It only
           forwards the grandchild's exit status (waitpid below). */
        int st = 0;
        while (waitpid(pid, &st, 0) < 0 && errno == EINTR) {}
        lua_pushboolean(L, 1);
        return 1;
    }

    /* --- intermediate child: double-fork, reap the grandchild, _exit. ---
       The grandchild does the transfer; once reparented to init it cannot
       leave a zombie in this process, and SIGCHLD stays default so
       system()/tether.exec keep reporting real exit codes. */
    pid_t gpid = fork();
    if (gpid > 0) {
        int gst = 0;
        while (waitpid(gpid, &gst, 0) < 0 && errno == EINTR) {}
        _exit(0);
    }
    if (gpid < 0)
        _exit(1); /* no grandchild: nothing will write the outpath anyway */

    /* --- grandchild: fetch, write, _exit. No terminal, no Lua, no return. --- */
    int devnull = open("/dev/null", O_RDWR);
    if (devnull >= 0) {
        dup2(devnull, STDIN_FILENO);
        dup2(devnull, STDOUT_FILENO);
        dup2(devnull, STDERR_FILENO);
        if (devnull > 2)
            close(devnull);
    }

    CURL *h = curl_easy_init();
    struct body_buf body;
    memset(&body, 0, sizeof(body));
    long status = 0;
    CURLcode rc = CURLE_FAILED_INIT;
    if (h != NULL) {
        http_apply_common(h, url, ca, headers);
        curl_easy_setopt(h, CURLOPT_HTTPGET, 1L);
        curl_easy_setopt(h, CURLOPT_TIMEOUT_MS, (long)(timeout_s * 1000.0));
        curl_easy_setopt(h, CURLOPT_WRITEFUNCTION, http_body_cb);
        curl_easy_setopt(h, CURLOPT_WRITEDATA, &body);
        rc = curl_easy_perform(h);
        curl_easy_getinfo(h, CURLINFO_RESPONSE_CODE, &status);
        curl_easy_cleanup(h);
    }
    curl_slist_free_all(headers);

    char tmp[4096];
    snprintf(tmp, sizeof(tmp), "%s.tmp.%d", outpath, (int)getpid());
    FILE *f = fopen(tmp, "w");
    if (f != NULL) {
        if (rc == CURLE_OK && status < 400 && body.data != NULL)
            fwrite(body.data, 1, body.len, f);
        else if (rc == CURLE_OK) {
            char msg[64];
            snprintf(msg, sizeof(msg), "http %ld", status);
            fprintf(f, "FETCH_FAILED %s\n", msg);
        } else {
            fprintf(f, "FETCH_FAILED %s\n", curl_easy_strerror(rc));
        }
        fclose(f);
        rename(tmp, outpath);
    }
    free(body.data);
    _exit(0);
}

/* tether.http_get(url, headers, timeout_s) -> body | nil, err
 *
 * timeout_s is the total request timeout in seconds (default 30). A status of
 * 400 or above is reported as nil, "http <status>" rather than as a body. */
static int l_http_get(lua_State *L)
{
    const char *url = luaL_checkstring(L, 1);
    double timeout_s = 30.0;
    if (lua_isnumber(L, 3))
        timeout_s = lua_tonumber(L, 3);

    const char *ca = tether_ca_bundle();
    if (ca == NULL) {
        lua_pushnil(L);
        lua_pushstring(L, "no system CA bundle found");
        return 2;
    }

    char err[256] = {0};
    struct curl_slist *headers = http_build_headers(L, 2, err, sizeof(err));
    if (err[0] != '\0') {
        lua_pushnil(L);
        lua_pushstring(L, err);
        return 2;
    }

    CURL *h = curl_easy_init();
    if (h == NULL) {
        curl_slist_free_all(headers);
        lua_pushnil(L);
        lua_pushstring(L, "cannot create HTTP handle");
        return 2;
    }

    struct body_buf body;
    memset(&body, 0, sizeof(body));

    http_apply_common(h, url, ca, headers);
    curl_easy_setopt(h, CURLOPT_HTTPGET, 1L);
    curl_easy_setopt(h, CURLOPT_TIMEOUT_MS, (long)(timeout_s * 1000.0));
    curl_easy_setopt(h, CURLOPT_WRITEFUNCTION, http_body_cb);
    curl_easy_setopt(h, CURLOPT_WRITEDATA, &body);
    /* same steady tick as the stream path (a /models refresh mid-turn
       stalled the spinner for up to timeout_s); abort comes free. */
    curl_easy_setopt(h, CURLOPT_NOPROGRESS, 0L);
    curl_easy_setopt(h, CURLOPT_XFERINFOFUNCTION, http_xferinfo);
    curl_easy_setopt(h, CURLOPT_XFERINFODATA, (void *)L);

    CURLcode rc = stream_perform(h, L);
    long status = 0;
    curl_easy_getinfo(h, CURLINFO_RESPONSE_CODE, &status);
    curl_slist_free_all(headers);
    curl_easy_cleanup(h);

    if (rc != CURLE_OK) {
        free(body.data);
        lua_pushnil(L);
        lua_pushstring(L, curl_easy_strerror(rc));
        return 2;
    }
    if (status >= 400) {
        free(body.data);
        char msg[64];
        snprintf(msg, sizeof(msg), "http %ld", status);
        lua_pushnil(L);
        lua_pushstring(L, msg);
        return 2;
    }
    lua_pushlstring(L, body.data ? body.data : "", body.len);
    free(body.data);
    return 1;
}

static int l_resize_requested(lua_State *L)
{
    lua_pushboolean(L, g_resize_requested);
    g_resize_requested = 0;
    return 1;
}

/* T15: sleep — used by API retry backoff. add-retry-and-continuation: the wait
   wakes as soon as input arrives (a Ctrl+C during a backoff ends the wait
   instead of being read only after the turn it was meant to interrupt), and it
   still lasts its requested duration when nothing arrives. */
static int l_sleep(lua_State *L)
{
    double secs = luaL_optnumber(L, 1, 0.0);
    if (secs <= 0.0) return 0;
    if (g_stdin_eof) {
        /* nothing to watch: a poll on a closed stdin would return at once.
           Still sleep in spinner quanta so the tick fires here too. */
        double left = secs;
        while (left > 0.0) {
            double slice = left > (double)SPINNER_QUANTUM_MS / 1000.0
                ? (double)SPINNER_QUANTUM_MS / 1000.0 : left;
            struct timespec ts;
            ts.tv_sec = (time_t)slice;
            ts.tv_nsec = (long)((slice - (double)ts.tv_sec) * 1e9);
            nanosleep(&ts, NULL);
            left -= slice;
            spinner_tick_call(L);
        }
        return 0;
    }
    struct timespec start, now;
    clock_gettime(CLOCK_MONOTONIC, &start);
    for (;;) {
        if (poll_interrupt()) return 0; /* interrupted: end the wait now */
        clock_gettime(CLOCK_MONOTONIC, &now);
        double elapsed = (double)(now.tv_sec - start.tv_sec)
            + (double)(now.tv_nsec - start.tv_nsec) / 1e9;
        double remaining = secs - elapsed;
        if (remaining <= 0.0) break;
        int ms = (int)(remaining * 1000.0);
        /* bounded: re-check the flag on the spinner cadence. The retry
           backoff sleeps here with no transfer in flight, so without a tick
           the spinner froze for the whole wait (the tick itself throttles
           to the same quantum, so firing it every loop is safe). */
        if (ms > SPINNER_QUANTUM_MS) ms = SPINNER_QUANTUM_MS;
        struct pollfd pfd;
        pfd.fd = STDIN_FILENO;
        pfd.events = POLLIN;
        pfd.revents = 0;
        poll(&pfd, 1, ms); /* returns early when the user types */
        spinner_tick_call(L);
    }
    return 0;
}/* add-retry-and-continuation: does the user want this turn stopped? The flag
   stays set until clear_abort(), because the very same Ctrl+C has to keep
   aborting an in-flight transfer (http_xferinfo) until the turn has actually
   stopped — only the turn knows when that happened. */
static int l_abort_requested(lua_State *L)
{
    poll_interrupt();
    lua_pushboolean(L, g_interrupt != 0);
    return 1;
}

/* TW2: monotonic wall-clock milliseconds. The spinner frame must derive from
   elapsed time (pi's Loader animates on an 80 ms interval), not from the paint
   counter — a frame per event made the spinner a slideshow whose speed
   depended on how fast tokens arrived. os.clock() is CPU time and stalls while
   the process blocks on IO; this clock is CLOCK_MONOTONIC. */
static int l_monotonic_ms(lua_State *L)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    lua_pushnumber(L, (double)ts.tv_sec * 1000.0 + (double)ts.tv_nsec / 1e6);
    return 1;
}

/* Drop a stale interrupt when a turn starts. */
static int l_clear_abort(lua_State *L)
{
    (void)L;
    g_interrupt = 0;
    return 0;
}

static int l_detect_kb_protocol(lua_State *L)
{
    const char *tp = getenv("TERM_PROGRAM");
    const char *tm = getenv("TERM");
    if (tp && (strstr(tp, "kitty") || strstr(tp, "Kitty"))) {
        lua_pushinteger(L, 1); /* kitty */
        return 1;
    }
    if ((tp && (strstr(tp, "VTE") || strstr(tp, "alacritty") || strstr(tp, "gnome"))) ||
        (tm && (strstr(tm, "xterm") || strstr(tm, "vte") || strstr(tm, "gnome")))) {
        lua_pushinteger(L, 2); /* modifyOtherKeys */
        return 1;
    }
    lua_pushinteger(L, 0); /* plain */
    return 1;
}

static int l_xfer_gc(lua_State *L)
{
    struct http_xfer **pp = luaL_checkudata(L, 1, "tether.http_xfer");
    if (pp != NULL && *pp != NULL) {
        xfer_destroy(*pp);
        *pp = NULL;
    }
    return 0;
}

static luaL_Reg tether_api[] = {
    {"read_char",       l_read_char},
    {"read_char_nb",    l_read_char_nb},
    {"write",           l_write},
    {"exec",        l_exec},
    {"rs256_sign",     l_rs256_sign},
    {"realpath",    l_realpath},
    {"getcwd",      l_getcwd},
    {"is_tty",      l_tty},
    {"get_terminal_size", l_get_terminal_size},
    {"mkdirp",      l_mkdirp},
    {"fchmod",      l_fchmod},
    {"readdir",     l_readdir},
    {"stat",        l_stat},
    {"krep_search", l_krep_search},
    {"http_stream", l_http_stream},
    {"http_get",    l_http_get},
    {"http_start",  l_http_start},
    {"http_step",   l_http_step},
    {"http_lines",  l_http_lines},
    {"http_abort",  l_http_abort},
    {"http_free",   l_http_free},
    {"http_fds",    l_http_fds},
    {"poll",        l_poll},
    {"set_tick_hook", l_set_tick_hook},
    {"fetch_bg",    l_fetch_bg},
    {"resize_requested", l_resize_requested},
    {"sleep",         l_sleep},
    {"abort_requested", l_abort_requested},
    {"clear_abort",   l_clear_abort},
    {"detect_kb_protocol", l_detect_kb_protocol},
    {"monotonic_ms",  l_monotonic_ms},
    {NULL, NULL}
};

static void open_tether_api(lua_State *L)
{
    /* idempotent; needed before any libcurl use (TLS backend init, zlib) */
    curl_global_init(CURL_GLOBAL_DEFAULT);
    luaL_newlib(L, tether_api);
    lua_setglobal(L, "tether");
    luaL_newmetatable(L, "tether.http_xfer");
    lua_pushcfunction(L, l_xfer_gc);
    lua_setfield(L, -2, "__gc");
    lua_pop(L, 1);
}

/* Load a Lua chunk, execute it, store its single return value in global `name`. */
static int load_module(lua_State *L, const char *src, const char *name)
{
    int lr = luaL_loadstring(L, src);
    if (lr != LUA_OK) {
        fprintf(stderr, "tether: load %s: %s\n", name, lua_tostring(L, -1));
        lua_pop(L, 1);
        return 1;
    }
    lr = lua_pcall(L, 0, 1, 0);
    if (lr != LUA_OK) {
        fprintf(stderr, "tether: run %s: %s\n", name, lua_tostring(L, -1));
        lua_pop(L, 1);
        return 1;
    }
    if (lua_isnil(L, -1)) {
        lua_pop(L, 1);
        lua_newtable(L);
    }
    lua_setglobal(L, name);
    return 0;
}

int main(int argc, char **argv)
{
    int interactive = isatty(STDIN_FILENO) == 1;

    /* Install signal handling in every mode: SIGINT/SIGTERM restore the
       terminal (no-op when raw mode was never enabled) and exit cleanly.
       SIGWINCH only matters for the TUI. */
    setup_signal_handlers();

    if (interactive) {
        if (init_termios() != 0) {
            perror("tcsetattr");
            return 1;
        }
        atexit(restore_termios);
    }

    lua_State *L = luaL_newstate();
    if (!L) {
        fprintf(stderr, "tether: cannot allocate lua state\n");
        restore_termios();
        return 1;
    }
    luaL_openlibs(L);
    open_tether_api(L);

    int rc = 0;
    struct { const char *src; const char *name; } mods[] = {
        /* provider_common first: session/agent resolve their JSON helpers to it */
        { provider_common_lua,    "provider_common"    },
        /* provider_catalog next: api/config/ui resolve presets from it —
           must precede every module that reads it (config, ui, api) */
        { provider_catalog_lua, "provider_catalog" },
        /* retry: pure policy module api/agent apply (see src/tether/retry.lua) */
        { retry_lua,   "retry"   },
        { session_lua, "session" },
        { diff_lua,   "diff"   },
        /* ask: the structured-question rules ui/agent apply (src/tether/ask.lua) */
        { ask_lua,    "ask"    },
        /* confirm_policy: pure should_confirm/approve_key policy (src/tether/confirm_policy.lua) */
        { confirm_policy_lua, "confirm_policy" },
        /* auth: OAuth/API-key store for /login /logout (src/tether/auth.lua) */
        { auth_lua, "auth" },
        /* reactor: single-threaded event loop over stdin+transport+timers */
        { reactor_lua, "reactor" },
        /* transcript: visible conversation model; ui loads it before State */
        { transcript_lua, "transcript" },
        /* commands: session lifecycle + slash side effects (src/tether/commands.lua) */
        { commands_lua, "commands" },
        /* turn: control facade over agent; abort seam + busy reset (src/tether/turn.lua) */
        { turn_lua, "turn" },
        { ui_lua,     "ui"     },
        { config_lua, "config" },
        { tools_lua,  "tools"  },
        /* provider_catalog: preset table api/config/ui resolve (Tier-A adds no modules) */
        { provider_openai_lua,    "provider_openai"    },
        { provider_anthropic_lua, "provider_anthropic" },
        { provider_gemini_lua,    "provider_gemini"    },
        /* Tier-B adapters (own wire/auth, before api) */
        { provider_azure_openai_lua,          "provider_azure_openai"          },
        { provider_amazon_bedrock_lua,        "provider_amazon_bedrock"        },
        { provider_google_vertex_lua,         "provider_google_vertex"         },
        { provider_cloudflare_ai_gateway_lua, "provider_cloudflare_ai_gateway" },
        { provider_radius_lua,                "provider_radius"                },
        { provider_openai_codex_lua,          "provider_openai_codex"          },
        { api_lua,    "api"    },
        { context_lua, "context" },
        { agent_lua,  "agent"  },
        { app_lua,    "app"    },
    };
    for (size_t i = 0; i < sizeof(mods)/sizeof(mods[0]); i++) {
        if (load_module(L, mods[i].src, mods[i].name) != 0) { rc = 1; break; }
    }
    if (rc == 0) {
        /* Push argv to Lua 'arg' global for CLI parsing */
        lua_newtable(L);
        for (int i = 1; i < argc; i++) {
            lua_pushstring(L, argv[i]);
            lua_rawseti(L, -2, i);
        }
        lua_setglobal(L, "arg");
        lua_getglobal(L, "app");
        lua_getfield(L, -1, "run");
        int rc2 = lua_pcall(L, 0, 0, 0);
        if (rc2 != LUA_OK) {
            fprintf(stderr, "tether: app.run: %s\n", lua_tostring(L, -1));
            lua_pop(L, 1);
            rc = 1;
        }
        lua_pop(L, 1);
    }

    lua_close(L);
    restore_termios();
    return rc == 0 ? 0 : 1;
}
