#!/usr/bin/env lua
-- tools/embed.lua — embeds .lua files as C byte arrays into src/host/embed.c
-- usage: lua tools/embed.lua <out.c> <name1> <path1> [<name2> <path2> ...]
local out = assert(arg[1], "usage: embed.lua <out.c> <name> <path> ...")
local files = {}
for i = 2, #arg, 2 do
  local name, path = arg[i], arg[i + 1]
  local f = assert(io.open(path, "rb"), "cannot open " .. path)
  local data = f:read("a")
  f:close()
  files[#files + 1] = { name = name, data = data }
end

local w = io.open(out, "wb")
assert(w, "cannot write " .. out)
w:write("/* generated by tools/embed.lua — do not edit */\n")
w:write('#include <stddef.h>\n\n')
for _, f in ipairs(files) do
  local nm  = f.name
  local arr = nm .. "_arr"
  w:write(string.format("const unsigned char %s[] = {\n", arr))
  for i = 1, #f.data do
    local b = string.byte(f.data, i)
    w:write(string.format("  0x%02x,", b))
    if i % 12 == 0 then w:write("\n") end
  end
  w:write("  0x00,\n")
  w:write("};\n\n")
  w:write(string.format("const char *%s = (const char *)%s;\n\n", nm, arr))
end
w:close()
