#!/usr/bin/env lua
-- tools/gen-snapshot.lua — slim provider snapshot for embedding.
-- usage: lua tools/gen-snapshot.lua <data/providers.json> <build/providers_snapshot.lua>
--
-- Strips models[] (the live provider API + lazy metadata replace them) and
-- keeps schema + generated_at. Output is a Lua module returning the slim
-- JSON string; catalog.parse_file validates it at runtime exactly like the
-- cache file, so no second validator exists. Deterministic: keys are
-- re-emitted in sorted order by provider_common.json_encode.
local inf, outf = arg[1], arg[2]
assert(inf and outf, "usage: gen-snapshot.lua <in.json> <out.lua>")

local common = assert(loadfile("src/tether/providers/common.lua"))()
local catalog = assert(loadfile("src/tether/providers/catalog.lua"))()

local f = assert(io.open(inf, "rb"), "cannot open " .. inf)
local body = f:read("a")
f:close()

local tbl = common.json_decode(body)
assert(type(tbl) == "table" and tbl.schema ~= nil, "bad providers file")
assert(type(tbl.providers) == "table", "providers file has no providers table")

local slim_providers = {}
for id, e in pairs(tbl.providers) do
    -- slim_entry is the single source of the snapshot shape (see catalog).
    local s = catalog.slim_entry(e)
    if s then slim_providers[id] = s end
end
local slim = { schema = tbl.schema, generated_at = tbl.generated_at,
               providers = slim_providers }
local payload = common.json_encode(slim)

-- long-bracket level that cannot collide with the payload.
local level = 0
while payload:find("%]" .. string.rep("=", level) .. "%]", 1, true) do
    level = level + 1
end
local eq = string.rep("=", level)

local w = assert(io.open(outf, "wb"), "cannot write " .. outf)
w:write("-- generated by tools/gen-snapshot.lua from " .. inf
    .. " — do not edit\n")
w:write("return [" .. eq .. "[" .. payload .. "]" .. eq .. "]\n")
w:close()
