#!/usr/bin/env lua
-- tools/gen-version.lua — build version string for embedding.
-- usage: lua tools/gen-version.lua <out.lua> [version]
--
-- Precedence: explicit arg > TETHER_VERSION env > git short hash > "dev".
-- CI fresh-clones, so the git hash is current; tarball builds without
-- .git land on "dev" (override with the arg or env for release builds).
-- Output is a Lua module returning the version string (no "v" prefix).
local outf, given = arg[1], arg[2]
assert(outf, "usage: gen-version.lua <out.lua> [version]")

local v = given
if not v or v == "" then v = os.getenv("TETHER_VERSION") end
if not v or v == "" then
    local h = io.popen("git rev-parse --short HEAD 2>/dev/null")
    if h then
        v = h:read("*a") or ""
        h:close()
    end
    v = (v or ""):match("^%s*(.-)%s*$")
end
if not v or v == "" then v = "dev" end

-- Idempotent: keep the mtime when the version is unchanged, so make does
-- not re-embed (and relink) on every build. A stale mtime once shipped a
-- binary whose --version named a month-old commit.
local body = "-- generated by tools/gen-version.lua — do not edit\n"
    .. "return " .. string.format("%q", v) .. "\n"
do
    local f = io.open(outf, "rb")
    if f then
        local cur = f:read("*a")
        f:close()
        if cur == body then return end
    end
end

local w = assert(io.open(outf, "wb"), "cannot write " .. outf)
w:write(body)
w:close()
