#!/usr/bin/env lua
-- tools/gen_embed.lua — derive Lua module registration from tools/embed_order.txt.
-- usage: lua tools/gen_embed.lua <orderfile> <out.mk> <out.inc>
--
-- Reads [embed] (varname/path, byte layout) and [load] (varname refs +
-- `##` ordering comments). Writes:
--   out.mk:  LUA_MODS line + EMBED_ARGS block (tab-indented, trailing `\`
--            on every line but the last, exactly as the Makefile had them).
--   out.inc: main.c mods[] initializer lines + /* */ ordering comments,
--            uniform single-space padding (historical hand alignment is
--            intentionally NOT reproduced — see task 1.1 note).
local orderfile, out_mk, out_inc = arg[1], arg[2], arg[3]
assert(orderfile and out_mk and out_inc, "usage: gen_embed.lua <orderfile> <out.mk> <out.inc>")

local paths, embed, load = {}, {}, {}
local section = nil
for line in io.lines(orderfile) do
    local s = line:match("^%s*(.-)%s*$")
    if s == "" or s:sub(1, 1) == "#" and s:sub(1, 2) ~= "##" then
        -- blank or file comment; `##` handled per section below
    elseif s == "[embed]" then section = "embed"
    elseif s == "[load]" then section = "load"
    elseif section == "embed" then
        assert(s:sub(1, 1) ~= "#", "comments do not belong in [embed]: " .. line)
        local var, path = s:match("^(%S+)%s+(%S+)%s*$")
        assert(var and path, "bad [embed] line: " .. line)
        assert(not paths[var], "duplicate module: " .. var)
        paths[var] = path
        embed[#embed + 1] = var
    elseif section == "load" then
        if s:sub(1, 2) == "##" then
            load[#load + 1] = { comment = s:sub(3):match("^%s*(.-)%s*$") }
        else
            local var = s:match("^(%S+)%s*$")
            assert(var, "bad [load] line: " .. line)
            assert(paths[var], "load entry without [embed] entry: " .. var)
            load[#load + 1] = { var = var }
        end
    else
        error("line outside [embed]/[load]: " .. line)
    end
end
assert(#embed > 0 and #load > 0, "empty order file")

-- every embedded module loads exactly once; every loaded module embeds.
local seen = {}
for _, e in ipairs(load) do
    if e.var then
        assert(not seen[e.var], "duplicate [load] entry: " .. e.var)
        seen[e.var] = true
    end
end
for _, var in ipairs(embed) do
    assert(seen[var], "embedded but never loaded: " .. var)
end

local mk = io.open(out_mk, "wb")
assert(mk, "cannot write " .. out_mk)
mk:write("# generated by tools/gen_embed.lua from " .. orderfile .. " — do not edit\n")
local modpaths = {}
for _, var in ipairs(embed) do modpaths[#modpaths + 1] = paths[var] end
mk:write("LUA_MODS = " .. table.concat(modpaths, " ") .. "\n")
mk:write("EMBED_ARGS = \\\n")
for i, var in ipairs(embed) do
    local tail = (i == #embed) and "\n" or " \\\n"
    mk:write("\t\t" .. var .. "_lua " .. paths[var] .. tail)
end
mk:close()

local inc = io.open(out_inc, "wb")
assert(inc, "cannot write " .. out_inc)
inc:write("/* generated by tools/gen_embed.lua — do not edit */\n")
local pending = {} -- consecutive ## lines merge into one /* */ block
local function flush_comments()
    if #pending == 0 then return end
    if #pending == 1 then
        inc:write("        /* " .. pending[1] .. " */\n")
    else
        inc:write("        /* " .. pending[1] .. "\n")
        for i = 2, #pending do
            local close = (i == #pending) and " */\n" or "\n"
            inc:write("           " .. pending[i] .. close)
        end
    end
    pending = {}
end
for _, e in ipairs(load) do
    if e.comment ~= nil then
        pending[#pending + 1] = e.comment
    else
        flush_comments()
        inc:write("        { " .. e.var .. "_lua, \"" .. e.var .. "\" },\n")
    end
end
flush_comments()
inc:close()
print("gen_embed: " .. #embed .. " modules, " .. #load .. " load lines")
